// prettier-ignore
export const Classic = [
  ['Classic', 'both', 'truth', 1, 'Who is your favorite family member?'],
  ['Classic', 'both', 'truth', 1, 'What is your least favorite part about family gatherings?'],
  ['Classic', 'both', 'truth', 3, 'What is the biggest secret that you kept from your parents when you were growing up?'],
  ['Classic', 'both', 'truth', 1, 'What is your favorite movie that you secretly know is actually terrible?'],
  ['Classic', 'both', 'truth', 2, 'What is your worst habit?'],
  ['Classic', 'both', 'truth', 3, 'Have you ever bribed or flirted with a police officer to get out of a ticket?'],
  ['Classic', 'both', 'truth', 2, 'What is something you most look forward to doing when you retire?'],
  ['Classic', 'both', 'truth', 2, 'Do you have a bucket list? If so, what is one thing on that list?'],
  ['Classic', 'both', 'truth', 2, 'What is one thing you are always losing?'],
  ['Classic', 'both', 'truth', 1, 'What is the strangest thing you have ever bought?'],
  ['Classic', 'both', 'truth', 2, 'Do you have a weird collection? If so, what?'],
  ['Classic', 'both', 'truth', 3, 'Tell us about the last dream you can remember. Don’t leave any details out!'],
  ['Classic', 'both', 'truth', 3, 'Have you ever shared chewing gum with anyone?'],
  ['Classic', 'both', 'truth', 2, 'Have you ever lied about being sick so you could stay home from work or school?'],
  ['Classic', 'both', 'truth', 2, 'If you could do one thing you did when you were a child, what would it be?'],
  ['Classic', 'both', 'truth', 3, 'Have you ever danced on a table when you were drunk?'],
  ['Classic', 'both', 'truth', 2, 'Have you ever told someone you wouldn’t be home just so they wouldn’t come over to yours?'],
  ['Classic', 'both', 'truth', 1, 'What is the one thing you dislike about yourself?'],
  ['Classic', 'both', 'truth', 1, 'What is the one thing you really like about yourself?'],
  ['Classic', 'both', 'truth', 1, 'What is the one thing you would stand in line for?'],
  ['Classic', 'both', 'truth', 2, 'Have you ever lied on your resume to get a job?'],
  ['Classic', 'both', 'truth', 3, 'If anyone in your family could win an award for being the most annoying, who would it be?'],
  ['Classic', 'both', 'truth', 3, 'What is the most embarrassing thing that has happened to you in front of a crowd?'],
  ['Classic', 'both', 'truth', 2, 'What is your least favorite household chore?'],
  ['Classic', 'both', 'truth', 2, 'If you could hire someone to do one thing for you, what would it be?'],
  ['Classic', 'both', 'truth', 3, 'What was the most embarrassing thing that you ever did while on a date?'],
  ['Classic', 'both', 'truth', 2, 'What was the worst gift you ever received?'],
  ['Classic', 'both', 'truth', 1, 'What is the one thing you are the most afraid of?'],
  ['Classic', 'both', 'truth', 3, 'Have you ever sent an inappropriate text to your mom or dad by accident?'],
  ['Classic', 'both', 'truth', 2, 'Have you ever bought something to wear to an event and then returned it to the store when the event was over?'],
  ['Classic', 'both', 'truth', 1, 'Have you ever fallen asleep in church?'],
  ['Classic', 'both', 'truth', 1, 'Did you ever break up with someone just before a public holiday so that you didn’t have to buy them a gift?'],
  ['Classic', 'both', 'truth', 1, 'Have you ever kept a library book?'],
  ['Classic', 'both', 'truth', 2, 'Have you ever cheated on a test?'],
  ['Classic', 'both', 'truth', 2, 'If you could create your own job title, what would it be?'],
  ['Classic', 'both', 'truth', 2, 'What is your excuse to get out of exercising?'],
  ['Classic', 'both', 'truth', 2, 'What was the one thing you could never learn how to do no matter how hard you tried?'],
  ['Classic', 'both', 'truth', 1, 'What was your favorite childhood television show?'],
  ['Classic', 'both', 'truth', 3, 'Did you ever sneak into an adult movie when you were underage?'],
  ['Classic', 'both', 'truth', 2, 'If you had a remote control that would operate anything, what would you control?'],
  ['Classic', 'both', 'truth', 2, 'Have you ever complained about something at a restaurant just to get out of paying?'],
  ['Classic', 'both', 'truth', 1, 'What is one thing you did as a child that you still enjoy?'],
  ['Classic', 'both', 'truth', 1, 'Do you prefer the big city or country life?'],
  ['Classic', 'both', 'truth', 2, 'What is your guilty pleasure?'],
  ['Classic', 'both', 'truth', 1, 'What are your favorite pizza toppings?'],
  ['Classic', 'both', 'truth', 1, 'Where is your favorite vacation spot?'],
  ['Classic', 'both', 'truth', 1, 'Have you ever used a work computer for personal use?'],
  ['Classic', 'both', 'truth', 2, 'What is your favorite thing to do with your leisure time?'],
  ['Classic', 'both', 'truth', 2, 'What was the worst vacation you ever had?'],
  ['Classic', 'both', 'truth', 1, 'If you were to bury a time capsule, what is one thing you would put in it?'],
  ['Classic', 'both', 'truth', 3, 'If you were granted three wishes, what would they be?'],
  ['Classic', 'both', 'truth', 1, 'What is your favorite holiday?'],
  ['Classic', 'both', 'truth', 1, 'What is your biggest pet peeve?'],
  ['Classic', 'both', 'truth', 2, 'If you could choose a different career, what would it be and why?'],
  ['Classic', 'both', 'truth', 2, 'If you could live anywhere in the world, where would it be?'],
  ['Classic', 'both', 'truth', 1, 'What is your favorite snack from a vending machine?'],
  ['Classic', 'both', 'truth', 2, 'Have you ever forgotten a special person’s birthday?'],
  ['Classic', 'both', 'truth', 1, 'Have you ever taken a drink straight out of the carton?'],
  ['Classic', 'both', 'truth', 1, 'On a scale from 1-10, where does your patience fall?'],
  ['Classic', 'both', 'truth', 2, 'If animals could talk, which one would you have a conversation with?'],
  ['Classic', 'both', 'truth', 2, 'Tell us about the worst restaurant experience you ever had.'],
  ['Classic', 'both', 'truth', 3, 'Is there any movie that always makes you cry?'],
  ['Classic', 'both', 'truth', 2, 'Say the funniest joke you’ve ever heard.'],
  ['Classic', 'both', 'truth', 2, 'What is something you find absolutely disgusting to the point you get sick?'],
  ['Classic', 'both', 'truth', 3, 'Have you ever been stuck in an elevator and if so who were you with?'],
  ['Classic', 'both', 'truth', 1, 'Who was your favorite teacher in school?'],
  ['Classic', 'both', 'truth', 1, 'What was your favorite subject in school?'],
  ['Classic', 'both', 'truth', 2, 'What is something that you are not looking forward to?'],
  ['Classic', 'both', 'truth', 3, 'Knowing now what you didn’t know then, what would you have done differently?'],
  ['Classic', 'both', 'truth', 3, 'Have you ever told a secret after you were told not to?'],
  ['Classic', 'both', 'truth', 1, 'Are you always on time, or are you always late?'],
  ['Classic', 'both', 'truth', 1, 'Are you a morning person or a night person?'],
  ['Classic', 'both', 'truth', 2, 'What is one job you would never want to do?'],
  ['Classic', 'both', 'truth', 1, 'What is your favorite ice cream flavor?'],
  ['Classic', 'both', 'truth', 1, 'When you think that no one is listening, do you sing in the shower?'],
  ['Classic', 'both', 'truth', 2, 'The last time you argued with someone, did you apologize first or was it the other person?'],
  ['Classic', 'both', 'truth', 2, 'What is the best gift you ever received?'],
  ['Classic', 'both', 'truth', 1, 'Is there any food that you can never eat?'],
  ['Classic', 'both', 'truth', 1, 'What was your favorite childhood toy?'],
  ['Classic', 'both', 'truth', 1, 'If you were given a million dollars, what would you do with it?'],
  ['Classic', 'both', 'truth', 3, 'Have you ever been arrested?'],
  ['Classic', 'both', 'truth', 1, 'What is your favorite sport?'],
  ['Classic', 'both', 'truth', 1, 'What is your favorite ride at the amusement park?'],
  ['Classic', 'both', 'truth', 1, 'Do you prefer the beach or the mountains?'],
  ['Classic', 'both', 'truth', 1, 'Have you ever been on a train?'],
  ['Classic', 'both', 'truth', 3, 'If you found a large amount of money, would you keep it or would you try to find the owner?'],
  ['Classic', 'both', 'truth', 3, 'What is the angriest you’ve ever been?'],
  ['Classic', 'both', 'truth', 2, 'What makes you the happiest?'],
  ['Classic', 'both', 'truth', 1, 'What is your favorite sandwich?'],
  ['Classic', 'both', 'truth', 2, 'Is there anything you regret buying, and if so, what is it?'],
  ['Classic', 'both', 'truth', 2, 'What is the best thing you ever bought?'],
  ['Classic', 'both', 'truth', 3, 'If you were invisible what is something you would do?'],
  ['Classic', 'both', 'truth', 2, 'What makes you feel uncomfortable?'],
  ['Classic', 'both', 'truth', 1, 'Do you prefer cats, dogs, or neither?'],
  ['Classic', 'both', 'truth', 2, 'If there was one thing you could change about yourself, what would it be?'],
  ['Classic', 'both', 'truth', 3, 'If you were a giant, what would you like to do?'],
  ['Classic', 'both', 'truth', 1, 'What is your favorite music genre?'],
  ['Classic', 'both', 'truth', 1, 'Have you ever blamed your sibling for something you did just so that you wouldn’t get in trouble?'],
  ['Classic', 'both', 'truth', 1, 'How old were you when you got your first cell phone?'],
  ['Classic', 'both', 'truth', 2, 'When is the last time you took a shower?'],
  ['Classic', 'both', 'truth', 2, 'When is the last time you brushed your teeth?'],
  ['Classic', 'both', 'truth', 2, 'Describe your favorite activity when you’re alone.'],
  ['Classic', 'both', 'truth', 2, 'What do you like to do when you are with your friends?'],
  ['Classic', 'both', 'truth', 3, 'Who was your first crush?'],
  ['Classic', 'both', 'truth', 3, 'How old were you when you had your first crush?'],
  ['Classic', 'both', 'truth', 2, 'What is the best time of day for you?'],
  ['Classic', 'both', 'truth', 2, 'What is your least favorite time of the day?'],
  ['Classic', 'both', 'truth', 2, 'If you didn’t have to work, what would you do with all your time?'],
  ['Classic', 'both', 'truth', 1, 'Tell us about your favorite possession.'],
  ['Classic', 'both', 'truth', 2, 'Name the three websites you visit the most.'],
  ['Classic', 'both', 'truth', 1, 'What was the best day you ever had?'],
  ['Classic', 'both', 'truth', 1, 'Describe the worst day you’ve ever had.'],
  ['Classic', 'both', 'truth', 1, 'Say your biggest fear in life.'],
  ['Classic', 'both', 'truth', 1, 'Did you have a nickname as a child and if so, what was it?'],
  ['Classic', 'both', 'truth', 1, 'Do you prefer mushy movies or funny ones?'],
  ['Classic', 'both', 'truth', 2, 'If you only had two minutes to get out of your house, what would you grab?'],
  ['Classic', 'both', 'truth', 1, 'What is your favorite vegetable?'],
  ['Classic', 'both', 'truth', 1, 'What is your favorite fruit?'],
  ['Classic', 'both', 'truth', 2, 'Do you have a special talent and if so, what is it?'],
  ['Classic', 'both', 'truth', 1, 'Have you ever been married?'],
  ['Classic', 'both', 'truth', 1, 'What do you like to put on your toast?'],
  ['Classic', 'both', 'truth', 2, 'What is the spiciest thing you’ve ever eaten?'],
  ['Classic', 'both', 'truth', 2, 'If you could live anywhere in the world, where would it be?'],
  ['Classic', 'both', 'truth', 1, 'Do you prefer Facebook or Twitter?'],
  ['Classic', 'both', 'truth', 1, 'What season is your favorite?'],
  ['Classic', 'both', 'truth', 2, 'Who is your most annoying neighbor?'],
  ['Classic', 'both', 'truth', 3, 'If you could be someone else for a day who would you be?'],
  ['Classic', 'both', 'truth', 1, 'What was the name of the street you grew up on?'],
  ['Classic', 'both', 'truth', 1, 'Which do you like better, cars or trucks?'],
  ['Classic', 'both', 'truth', 1, 'What is your favorite outdoor pastime?'],
  ['Classic', 'both', 'truth', 1, 'Which do you like better, Coca-Cola or Pepsi?'],
  ['Classic', 'both', 'truth', 1, 'What is your favorite month and why?'],
  ['Classic', 'both', 'truth', 2, 'Do you like to read and if so, what is your favorite book?'],
  ['Classic', 'both', 'truth', 2, 'Have you ever met a celebrity, if so, who?'],
  ['Classic', 'both', 'truth', 3, 'Has there have been a time when you cheated to win a game?'],
  ['Classic', 'both', 'truth', 3, 'Have you ever sent a love message to your boss by accident that was meant for someone else?'],
  ['Classic', 'both', 'truth', 1, 'What food do you absolutely despise?'],
  ['Classic', 'both', 'truth', 3, 'Who is the person you are the most jealous of and why?'],
  ['Classic', 'both', 'truth', 2, 'How many different languages can you speak and what are they?'],
  ['Classic', 'both', 'truth', 3, 'Do you have any tattoos and if so, where?'],
  ['Classic', 'both', 'truth', 2, 'Have you ever been outside of the country?'],
  ['Classic', 'both', 'truth', 2, 'What is one thing your grandparents taught you how to do?'],
  ['Classic', 'both', 'truth', 2, 'Have you ever been to the opera?'],
  ['Classic', 'both', 'truth', 2, 'Do you prefer talking or texting?'],
  ['Classic', 'both', 'truth', 2, 'Have you ever had an argument with someone through text?'],
  ['Classic', 'both', 'truth', 1, 'What was the last thing you ate?'],
  ['Classic', 'both', 'truth', 1, 'Have you ever been to the zoo?'],
  ['Classic', 'both', 'truth', 2, 'What is the grossest thing you’ve ever eaten?'],
  ['Classic', 'both', 'truth', 3, 'What is your most regrettable kiss?'],
  ['Classic', 'both', 'truth', 1, 'Have you ever failed a test? What was it?'],
  ['Classic', 'both', 'truth', 1, 'Who is your favorite teacher and why?'],
  ['Classic', 'both', 'truth', 3, 'Who was your longest secret crush?'],
  ['Classic', 'both', 'truth', 2, 'Where do you like to go when you’re feeling down?'],
  ['Classic', 'both', 'truth', 1, 'What is your favorite song?'],
  ['Classic', 'both', 'truth', 3, 'What is something you have never told anyone in this room?'],
  ['Classic', 'both', 'truth', 3, 'What do you like to wear when no one is around?'],
  ['Classic', 'both', 'truth', 3, 'Who would rather be stuck on a desert island: the person on your left or on your right?'],
  ['Classic', 'both', 'truth', 1, 'For parents: which is your favorite child? For children: which is your favorite parent?'],
  ['Classic', 'both', 'truth', 3, 'Have you ever shoplifted or stolen anything?'],
  ['Classic', 'both', 'truth', 3, 'Describe the worst date you’ve ever been on.'],
  ['Classic', 'both', 'truth', 2, 'If you could be fluent in one of these languages which would it be: Chinese, French or Russian?'],
  ['Classic', 'both', 'dare', 3, 'Completely cover yourself in toilet paper to look like a mummy.'],
  ['Classic', 'both', 'dare', 2, 'Randomly call a person from your phone and sing them a song.'],
  ['Classic', 'both', 'dare', 3, 'Call a family member of someone in the room and explain why you love your friend so much.'],
  ['Classic', 'both', 'dare', 2, 'Run outside and shout as loud as you can, “I am the best person in the world!”'],
  ['Classic', 'both', 'dare', 2, 'Mix all the sauces you have in your fridge and drink up.'],
  ['Classic', 'both', 'dare', 3, 'Prank call a friend’s partner.'],
  ['Classic', 'both', 'dare', 2, 'Call up a pizza place and order Chinese food.'],
  ['Classic', 'both', 'dare', 3, 'Take a shower without removing any of your clothes.'],
  ['Classic', 'both', 'dare', 3, 'Cover up your eyes (or wear a blindfold), and walk around the room for two minutes without watching where you’re going.'],
  ['Classic', 'both', 'dare', 2, 'Impersonate someone in the room and people have to guess who it is.'],
  ['Classic', 'both', 'dare', 1, 'Improvise and perform a two-minute comedy routine in front of everyone.'],
  ['Classic', 'both', 'dare', 3, 'Act like a dog for two minutes without laughing.'],
  ['Classic', 'both', 'dare', 2, 'Pour a freezing cold glass of water over your face without reacting.'],
  ['Classic', 'both', 'dare', 3, 'Talk about something you regret in your life.'],
  ['Classic', 'both', 'dare', 2, 'Tell a stranger walking past that you love them.'],
  ['Classic', 'both', 'dare', 1, 'Put as many pieces of cheese puffs in your mouth at one time as you can.'],
  ['Classic', 'both', 'dare', 2, 'Screenshot a picture of your browser history and send it to a random person in your contacts.'],
  ['Classic', 'both', 'dare', 2, 'Log into Facebook and like every picture for the past year of the first person you see.'],
  ['Classic', 'both', 'dare', 1, 'Rip off a piece of paper and eat it.'],
  ['Classic', 'both', 'dare', 3, 'Cover your hair with milk and don’t wash off until the end of the game.'],
  ['Classic', 'both', 'dare', 2, 'Text your mom the last picture saved on your phone.'],
  ['Classic', 'both', 'dare', 1, 'Pretend to be a chicken for 30 seconds.'],
  ['Classic', 'both', 'dare', 2, 'Stand up and run on the spot as fast as you can until it’s your turn.'],
  ['Classic', 'both', 'dare', 3, 'Sniff the player to your right’s armpit.'],
  ['Classic', 'both', 'dare', 2, 'Allow another player to throw flour in your face.'],
  ['Classic', 'both', 'dare', 1, 'Allow a random player to tickle you for 30 seconds.'],
  ['Classic', 'both', 'dare', 3, 'Go into the kitchen and take a bite out of something in the trash.'],
  ['Classic', 'both', 'dare', 2, 'Spritz perfume into your mouth.'],
  ['Classic', 'both', 'dare', 3, 'Head outside and lick a car tire.'],
  ['Classic', 'both', 'dare', 2, 'Take a picture of yourself pulling a funny face and set it as your Facebook profile picture for the rest of the day and night.'],
  ['Classic', 'both', 'dare', 3, 'Pass your phone to the person to your right and allow them to put any status on one of your social media accounts.'],
  ['Classic', 'both', 'dare', 1, 'Let someone in the group give you a wedgie.'],
  ['Classic', 'both', 'dare', 1, 'Grab a random object in the room and try and sell it to the group for two minutes.'],
  ['Classic', 'both', 'dare', 3, 'Kiss the second person to your left on the lips.'],
  ['Classic', 'both', 'dare', 1, 'Sing the chorus from a random song with all your heart.'],
  ['Classic', 'both', 'dare', 1, 'Speak in a baby’s voice for the next five things you have to say.'],
  ['Classic', 'both', 'dare', 2, 'Give someone in the group all the money you have in your purse.'],
  ['Classic', 'both', 'dare', 3, 'Take someone’s socks off and wear them like gloves for three minutes.'],
  ['Classic', 'both', 'dare', 3, 'Slap yourself in the face any time someone says “and” in the next three minutes.'],
  ['Classic', 'both', 'dare', 3, 'Blindfold yourself and let someone in the group feed you something of their choosing.'],
  ['Classic', 'both', 'dare', 2, 'Knock on your neighbor’s door and tell them how grateful they should be to live next to someone so awesome.'],
  ['Classic', 'both', 'dare', 2, 'Try to lick your elbow for the next three minutes.'],
  ['Classic', 'both', 'dare', 2, 'Laugh out loud at everything the person to your left says until it’s your turn.'],
  ['Classic', 'both', 'dare', 1, 'Stand up and try to break dance.'],
  ['Classic', 'both', 'dare', 1, 'Try to impersonate your favorite singer for one minute.'],
  ['Classic', 'both', 'dare', 1, 'Pick out the best and worst dressed individuals in the group.'],
  ['Classic', 'both', 'dare', 1, 'Act like you’re drunk for next three minutes.'],
  ['Classic', 'both', 'dare', 1, 'Hum a random song and you can’t stop until someone guesses what it is.'],
  ['Classic', 'both', 'dare', 2, 'Let someone bite your finger until it hurts.'],
  ['Classic', 'both', 'dare', 1, 'Attempt to keep your eyes as wind open as possible without blinking for next three minutes.'],
  ['Classic', 'both', 'dare', 2, 'Open a book, newspaper or magazine, and sing two random sentences as best you can.'],
  ['Classic', 'both', 'dare', 2, 'Show everyone the four most recent pictures on your phone.'],
  ['Classic', 'both', 'dare', 3, 'Write and perform a song that is at least two minutes long.'],
  ['Classic', 'both', 'dare', 3, 'Ring a random person from your phone and confess that you’re in love with a fictional character.'],
  ['Classic', 'both', 'dare', 1, 'Hold your breath for as long as you can.'],
  ['Classic', 'female', 'dare', 1, 'Apply makeup without looking in the mirror.'],
  ['Classic', 'both', 'dare', 3, 'Let a player write something on your head and don’t wipe it off until the end of the game.'],
  ['Classic', 'both', 'dare', 1, 'Do as many sit-ups as you can in one minute.'],
  ['Classic', 'both', 'dare', 2, 'Trade one item of clothing with another player and wear for the rest of the game.'],
  ['Classic', 'both', 'dare', 2, 'Try to sing a song with your mouth full of a drink.'],
  ['Classic', 'both', 'dare', 2, 'Eat a spoonful of a spicy sauce.'],
  ['Classic', 'both', 'dare', 1, 'Hold mouthwash in your mouth for as long as possible.'],
  ['Classic', 'both', 'dare', 3, 'Allow the second player to your right to make an alcoholic drink and you have to drink it as fast as you can.'],
  ['Classic', 'both', 'dare', 3, 'Completely shave off one of your eyebrows.'],
  ['Classic', 'both', 'dare', 3, 'Let someone wax half of your leg.'],
  ['Classic', 'both', 'dare', 3, 'Nibble at another player’s fingernails.'],
  ['Classic', 'both', 'dare', 3, 'Go outside and ask a stranger to smell your breath.'],
  ['Classic', 'both', 'dare', 3, 'Eat an entire onion without crying.'],
  ['Classic', 'both', 'dare', 3, 'Allow another player to cut a small chunk out of your hair.'],
  ['Classic', 'both', 'dare', 3, 'Massage another player’s back for five minutes.'],
  ['Classic', 'both', 'dare', 3, 'Sit among other players wearing only your underwear.'],
  ['Classic', 'both', 'dare', 3, 'Let another player keep any item of clothing from your wardrobe.'],
  ['Classic', 'both', 'dare', 2, 'Try to juggle with three eggs.'],
  ['Classic', 'both', 'dare', 1, 'Spank the person to your right.'],
  ['Classic', 'both', 'dare', 3, 'Confess your undying love to another player in the room.'],
  ['Classic', 'both', 'dare', 3, 'Blindfold yourself and allow another player to feed you something of their choosing, and you’ve got to guess what it is.'],
  ['Classic', 'both', 'dare', 3, 'Smell someone else’s shoes for 5 seconds.'],
  ['Classic', 'both', 'dare', 2, 'Text the last person you called saying, “I love you”.'],
  ['Classic', 'both', 'dare', 1, 'Speak in an accent chosen by another player for the rest of the game.'],
  ['Classic', 'both', 'dare', 1, 'Streak around the room for 10 seconds.'],
  ['Classic', 'both', 'dare', 1, 'Sit on someone else’s lap for a minutes.'],
  ['Classic', 'both', 'dare', 2, 'Allow another player to search anything they want on your phone.'],
  ['Classic', 'both', 'dare', 3, 'Eat an item of food off of someone’s face without using any hands.'],
  ['Classic', 'both', 'dare', 2, 'Passionately kiss the back of your hand and let someone record it.'],
  ['Classic', 'both', 'dare', 1, 'Describe someone else in the group and others have to guess who it is.'],
  ['Classic', 'both', 'dare', 1, 'Tell everyone about an embarrassing crush you once had.'],
  ['Classic', 'both', 'dare', 2, 'Grab a broom and pole dance for next 2 minutes.'],
  ['Classic', 'both', 'dare', 2, 'Whisper a secret about yourself to another player in the group.'],
  ['Classic', 'both', 'dare', 1, 'Perform your best air guitar routine without any music playing.'],
  ['Classic', 'both', 'dare', 3, 'Twerk wearing only your underwear.'],
  ['Classic', 'both', 'dare', 3, 'Let another player crack an egg on your head.'],
  ['Classic', 'both', 'dare', 3, 'Dress up like the opposite sex and let another player take a picture and upload it online.'],
  ['Classic', 'both', 'dare', 2, 'Put an ice cube down your pants and let it melt.'],
  ['Classic', 'both', 'dare', 3, 'Pretend that you’re a cat and rub up against the other players for one minute.'],
  ['Classic', 'both', 'dare', 2, 'Say the entire alphabet backward.'],
  ['Classic', 'both', 'dare', 2, 'Go to a neighbor’s house and ask if they have any spare food because you’re hungry.'],
  ['Classic', 'both', 'dare', 2, 'Make up a two-minute rap about an inanimate object in the room.'],
  ['Classic', 'both', 'dare', 2, 'Call the tenth contact on your phone and tell them all about your day, for no apparent reason.'],
  ['Classic', 'both', 'dare', 2, 'Head outside and talk to a random stranger as if they’re an old friend you haven’t seen in years.'],
  ['Classic', 'both', 'dare', 2, 'Balance an object on your head while walking around the room for one minute.'],
  ['Classic', 'both', 'dare', 2, 'Let the player to your left give you a new hairstyle for the rest of the game.'],
  ['Classic', 'both', 'dare', 3, 'Tell everyone an embarrassing story about yourself.'],
  ['Classic', 'both', 'dare', 2, 'Take a mouthful of water and tell a funny story about something that’s recently happened to you.'],
  ['Classic', 'both', 'dare', 2, 'Get down on one knee and pretend to propose to another player.'],
  ['Classic', 'both', 'dare', 1, 'Sing everything you want to say for the next 2 minutes.'],
  ['Classic', 'both', 'dare', 1, 'Eat as many pieces of bread as you can in two minutes.'],
  ['Classic', 'both', 'dare', 3, 'Lick a bar of soap from the bathroom.'],
  ['Classic', 'male', 'dare', 3, 'Text your mom that you’re going to be a dad.'],
  ['Classic', 'female', 'dare', 3, 'Text your mom and tell them you’re pregnant.'],
  ['Classic', 'both', 'dare', 3, 'Go outside and carry a sign that says “kiss me if you think I’m attractive”.'],
  ['Classic', 'both', 'dare', 2, 'Take a bite and swallow a piece of a banana skin.'],
  ['Classic', 'both', 'dare', 2, 'Lick an animal’s fur.'],
  ['Classic', 'both', 'dare', 2, 'Pretend that you’re a sheep for no reason whatsoever.'],
  ['Classic', 'both', 'dare', 1, 'Write a poem about why you are the best person in the world.'],
  ['Classic', 'both', 'dare', 1, 'Take a selfie with some old trash.'],
  ['Classic', 'both', 'dare', 1, 'Spank the closest person to you.'],
  ['Classic', 'both', 'dare', 3, 'Prank call your ex and tell them that you want to get back together.'],
  ['Classic', 'both', 'dare', 2, 'Eat a sandwich filled with ingredients chosen by other players.'],
  ['Classic', 'both', 'dare', 1, 'Put a teaspoon of salt in your mouth.'],
  ['Classic', 'both', 'dare', 2, 'Consume as many chilies as you can in two minutes.'],
  ['Classic', 'both', 'dare', 2, 'Head outside for a walk and talk aloud to yourself.'],
  ['Classic', 'both', 'dare', 2, 'Tell a stranger that you’re having a bad day and need someone to talk to.'],
  ['Classic', 'both', 'dare', 3, 'Lick the floor.'],
  ['Classic', 'both', 'dare', 1, 'Go outside and wink at the first person you see.'],
  ['Classic', 'both', 'dare', 2, 'Dance outside for two minutes without any music playing.'],
  ['Classic', 'both', 'dare', 1, 'Tell everyone about a celebrity crush you have.'],
  ['Classic', 'both', 'dare', 1, 'Take a picture of yourself pulling a funny pose and upload it to social media.'],
  ['Classic', 'both', 'dare', 1, 'Call a random person and wish them a happy birthday.'],
  ['Classic', 'both', 'dare', 1, 'Have a conversation with the TV.'],
  ['Classic', 'both', 'dare', 1, 'Act like you’re a child for two minutes.'],
  ['Classic', 'both', 'dare', 2, 'Drink an entire bottle of milk to yourself.'],
  ['Classic', 'both', 'dare', 2, 'Laugh like a hyena to everything everyone says until it’s your turn.'],
  ['Classic', 'both', 'dare', 2, 'Prank call a car breakdown company and say that you’re sad because you don’t have a car.'],
  ['Classic', 'both', 'dare', 2, 'Send a direct message to the last person you wrote to on Instagram saying that they’re beautiful.'],
  ['Classic', 'both', 'dare', 2, 'Give a stranger five dollars.'],
  ['Classic', 'both', 'dare', 3, 'Wash another player’s feet.'],
  ['Classic', 'both', 'dare', 3, 'Dip your hand in toilet water.'],
  ['Classic', 'both', 'dare', 3, 'Apply lipstick to your mouth and teeth and walk outside.'],
  ['Classic', 'both', 'dare', 2, 'Do a handstand with your feet against the wall and hold for 30 seconds.'],
  ['Classic', 'both', 'dare', 3, 'Give your phone to the person on your left and let them send any message they want to anybody on your contact list.'],
  ['Classic', 'both', 'dare', 2, 'Let the person to your right give you a temporary marker tattoo on your forehead of anything they want.'],
  ['Classic', 'both', 'dare', 2, 'Call your sibling or cousin and speak to them for one minute entirely in an Italian accent.'],
  ['Classic', 'both', 'dare', 2, 'Do the entire Gangnam Style dance using headphones so no one else hears the song.'],
  ['Classic', 'both', 'dare', 1, 'Sing your country’s national anthem while plugging your nose.'],
  ['Classic', 'both', 'dare', 3, 'Choose one other player and dance to the Titanic theme song while holding an orange between you (no hands). Don’t let the orange fall!'],
  ['Classic', 'both', 'dare', 3, 'Call your neighbor and make monkey sounds for 30 seconds straight.'],
  ['Classic', 'both', 'dare', 2, 'Make a love declaration to the player sitting opposite you.'],
  ['Classic', 'female', 'dare', 3, 'Do a belly dance to the tune of Ricky Martin’s “La Voda Loca”'],
  ['Classic', 'both', 'dare', 3, 'Email your favorite teacher and tell them you love them.'],
  ['Classic', 'both', 'dare', 3, 'Propose to the last person you sent a text message to.'],
];
