// prettier-ignore
export const CoupleDirty = [
  ['CoupleDirty', 'both', 'truth', 2, 'Where is the craziest place you’ve ever had sex?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Who was the worst you’ve ever had and the best you’ve ever had?'], 
  ['CoupleDirty', 'both', 'truth', 2, 'Read me your best sexting line in a sexy accent.'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the kinkiest thing you’ve ever done in bed?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the most adventurous thing you want to try in bed?'],
  ['CoupleDirty', 'both', 'truth', 2, 'How old were you when you lost your virginity and how did it go?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Who was your first kiss?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s a popular fetish that you would never want to try?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Do you remember the first time you experienced an orgasm? Tell me about it.'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s your favorite body part on your body?'],
  ['CoupleDirty', 'both', 'truth', 2, 'If you could have one sexual superpower, what would it be?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever been tempted to cheat on your significant other?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s your favorite position?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What position is popular that you think is overrated?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Do you think virginity is special?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What do you wish you had learned about sex way earlier than you did?'],
  ['CoupleDirty', 'both', 'dare', 2, 'Fake your best orgasm in front of me.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Do a mini strip tease by taking off some of your clothing in front of me.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Post something raunchy on your preferred social media app and you can’t remove it until the next round is over.'],
  ['CoupleDirty', 'both', 'dare', 2, 'You’ve been naughty, time to be put in time out on my lap for the next round.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Talk in a raunchy accent until your next turn.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Scroll blindly through your contacts and whoever you land on, say one sexy thing about them.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Give your best impression of a naughty cop who’s trying to arrest someone for being too sexy.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Send bold, dirty message to someone you’ve hooked up with before.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Take a pen and paper and draw your penis or vagina.'],
  ['CoupleDirty', 'female', 'dare', 2, 'Fake a blowjob on a bottle.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Describe your favorite position in detail but without saying what it is. Let me guess it!'],
  ['CoupleDirty', 'both', 'truth', 2, 'Would you rather be the person doing the spanking or be spanked yourself?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s something I do that unintentionally turns you on a lot?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s something I do in bed that turns you on a lot?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s something in bed that you would like me to try?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s a position you want to try?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Do you have anything you fear sexually?'],
  ['CoupleDirty', 'both', 'truth', 2, 'How often do you pleasure yourself a week?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever watched porn? What’s your go-to category?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Where is the craziest place you’ve ever masturbated?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s an odd fetish that you would try out?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the record amount of times you’ve had sex in one day?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever had sex while other people were in the room without them knowing?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Are you a fan of foreplay?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Are you a fan of shower sex?'],
  ['CoupleDirty', 'both', 'truth', 2, 'When’s the last time you pleasured yourself?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Do you enjoy receiving nudes?'],
  ['CoupleDirty', 'male', 'truth', 2, 'Have you ever been to a strip club? If not, would you like to go?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever wanted to try role play?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever masturbated with something weird?'],
  ['CoupleDirty', 'both', 'truth', 2, 'How old were you when you first watched porn?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever wanted to try bondage?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever received a lap dance?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s your favorite fantasy to pleasure yourself to?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What sex act have you done that you never want to do again?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever faked an orgasm with me?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Tell me about the best orgasm you’ve ever had.'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever had a crazy one-night stand? Tell me about it.'],
  ['CoupleDirty', 'both', 'truth', 2, 'If you woke up as the opposite sex, what’s the first thing you would explore about yourself.'],
  ['CoupleDirty', 'both', 'truth', 2, 'Do you like listening to music while having sex?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the longest you’ve gone without having sex?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s something sexy I say that you love?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever thought about experimenting with someone of the same sex?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever watched or wanted to watch another couple have sex?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Lights off or lights on during sex?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Where is your favorite place to have sex?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Does dirty talk get you horny?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Would you rather give or receive pleasure?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s a sexual act that you never want to try?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the dirtiest thing you’ve ever been caught doing or almost been caught doing?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s something you’ve fantasized about your partner that’s made you finish when pleasuring yourself before?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Do you like sex to be rough or sensual?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever been friend-zoned?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever paid for porn or sexual pleasure in any way?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the quickest way to get you into bed?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Do you prefer a little hair or smooth-shaven down there?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the least sexual thing your partner has done that’s gotten you aroused somehow?'],
  ['CoupleDirty', 'both', 'dare', 2, 'Have your partner read through your browsing history in a sexy voice.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Make a sexy song playlist with your partner.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Sexily wash your partner’s feet.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Be blindfolded and tickled or lightly touched for one minute.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Have your partner close their eyes and try to turn them on only using sounds.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Try to turn on your partner by blowing on the back of their neck, alternating between cold and CoupleDirty.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Place a hand in your partner’s underwear for the next round and try to arouse them.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Draw something on your partner’s back. If they guess correctly, they get a special favor of their choosing, if not, you get one.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Your partner gets to dress you up in their clothes and take a pCoupleDirtyo.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Call the parents of your partner and express to them how much you adore your partner.'],
  ['CoupleDirty', 'female', 'dare', 2, 'Give your partner a CoupleDirty lap dance.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Whisper something not sexy into your partner’s ear but try to make it sound CoupleDirty.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Describe your partner’s naked body in intense, erotic detail.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Wear handcuffs or have your hands tied for a few turns.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Trade clothes with your partner.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Take a body sCoupleDirty off your partner.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Show your partner your go-to porn video.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Give your partner a sexy full-body massage.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Give your phone to your partner and let them order something CoupleDirty for you to wear.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Turn on your partner by only touching their arms and hands.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Lick something yummy off your partner’s body part of choice.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Take off a piece of your partner’s clothing, only using your teeth.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Trace your partner’s body with an ice cube that’s being held in your mouth.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Beg your partner to do naughty things to you. It better be convincing!'],
  ['CoupleDirty', 'female', 'dare', 2, 'Give your partner head with their clothes on.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Do whatever your partner says for one minute.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Put on the CoupleDirtytest song you know and try to seduce your partner with it.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Make your best orgasm face and let your partner take a pCoupleDirtyo of it. This is your lock screen for the next 24 hours.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Become a sexy chef while teaching your partner how to make a fun late night snack while just wearing an apron.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Find an old pCoupleDirtyograph and try to recreate it together.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Have your partner ask 2 questions about themselves that you should know the answers to. If you get them right, you get a reward. If you get them wrong, you get punished.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Have your partner take a picture of you looking naughty.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Give your partner a massage without using your hands.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Act out how you remember your first date in 20 seconds.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Lick your partner’s feet for 25 seconds.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Set a timer and try to make your partner orgasm in 5 minutes.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Set a timer for 2 minutes and try not to get turned on by whatever your partner decides to do to you.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Watch porn together and try to imitate what you see on the screen.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Perform a strip tease for your partner.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Lick your partner’s nipples.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Kiss your partner in the sexiest place and sexiest way possible.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Undress your partner with one hand.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Suck on your partners finger like you’re giving them head.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Send a naughty text message to your partner.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Become a sexy chef and spank your partner sexily with an item from the kitchen.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Arouse your partner by only using your tongue.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Attempt to make a sex tape with your partner.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Let your partner blindfold you and do what they want to you for a minute.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Bend your partner over your knee and spank them while telling them they’re a bad boy/girl.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Sexily perform good foreplay on your partner’s ear to get them aroused.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Dress up in something your partner would find sexy.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Turn on your partner by sexily sucking on their finger.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Have your partner lay down and kiss them upside down the best you can.'],
  ['CoupleDirty', 'female', 'dare', 2, 'Give your partner a lesson on giving head to them with an object from the kitchen.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Have your partner spank you as hard as they can.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Whisper a sexy name in my ear that you’ve never called me but have thought about trying.'],
  ['CoupleDirty', 'male', 'dare', 2, 'Use a sex toy to try and get your partner in the mood.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Have your partner blindfold you and touch you with a part of their body. If you guess what part of their body they’re touching you with, you get a special reward.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Seduce your partner in a room where you have never had sex before.'],
  ['CoupleDirty', 'both', 'truth', 2, 'Describe to me in detail your sexiest pair of underwear.'],
  ['CoupleDirty', 'both', 'truth', 2, 'What was your first impression of me?'],
  ['CoupleDirty', 'both', 'truth', 2, 'When did you have your first sexual feelings?'],
  ['CoupleDirty', 'both', 'truth', 2, 'When was your first sexual experience?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What was your craziest sexual experience like?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Where is your favorite place to be kissed on your body?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the dirtiest thought you’ve ever had?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the dirtiest dream you’ve ever had?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Where’s the raunchiest place you dream of having sex?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Describe to me the best sex you’ve ever had.'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever had phone sex before?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Who’s the one that got away?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Are you turned on right now?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever been tied up before?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What is something that is completely off-limits from trying in bed?'],
  ['CoupleDirty', 'both', 'truth', 2, 'If you were to give a full body massage, where would you start and end?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What was your funniest sexual experience like?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever had sex in public? Would you or would you again?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What celebrity would you have sex with if you could?'],
  ['CoupleDirty', 'both', 'truth', 2, 'How can I get you horny?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever done something that you feel guilty about?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What was your biggest sexual disappointment?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever been sexually rejected?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Describe the funniest mistake that’s happened to you while having sex.'],
  ['CoupleDirty', 'both', 'truth', 2, 'Do you have a name for your penis or vagina?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What kinds of sex toys would you want to try?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever kissed someone of the same gender?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever flashed someone?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Do you like sexting?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever thought about me naked while talking to me?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What automatically makes you orgasm during sex?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever had or fantasized about an orgy?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever had or fantasized about a threesome?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever taken someone’s virginity?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What excites you the most in bed?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever masturbated in public?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s your wildest sexual fantasy?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What dirty secrets are you hiding?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever tried anal sex?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Do you like anal?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever done something sexy with food during sex or foreplay?'],
  ['CoupleDirty', 'both', 'dare', 2, 'Let your partner pick what profile picture you get to have for the remainder of the evening.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Demonstrate how you masturbate on an object in your room.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Give a tutorial on your best sexual technique on something in your room.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Slap yourself somewhere CoupleDirty.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Order your partner something to eat and they have to try whatever it is.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Change into the CoupleDirtytest outfit you have and pose in it like a model.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Cut off a little bit of your hair.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Draw something on your face with marker.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Try being sexy while holding your tongue and talking.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Pick two things from your kitchen and use them to act out your favorite sex position.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Order something sexy to wear when you see the other person.'],
  ['CoupleDirty', 'both', 'truth', 2, 'Describe what it was like the first time someone went down on you.'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever touched yourself while having sex?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the worst kiss you’ve ever had and why?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the best kiss you’ve ever had and why?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the most embarrassing wardrobe malfunction you’ve ever had?'],
  ['CoupleDirty', 'male', 'truth', 2, 'What’s the CoupleDirtytest body part on a guy?'],
  ['CoupleDirty', 'female', 'truth', 2, 'What’s the CoupleDirtytest body part on a girl?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the awkwardest crush you’ve ever had on someone?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Describe the sexual encounter you regret the most.'],
  ['CoupleDirty', 'both', 'truth', 2, 'What was it like the first time you went down on someone?'],
  ['CoupleDirty', 'female', 'truth', 2, 'Spit or swallow?'],
  ['CoupleDirty', 'both', 'truth', 2, 'How often do you shave down there?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever gotten a wax down there?'],
  ['CoupleDirty', 'both', 'truth', 2, 'If you were going to have a threesome, would you want the third party to be another girl or a guy?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever been to a strip club?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s something funny that turns you on?'],
  ['CoupleDirty', 'female', 'truth', 2, 'Do you get more horny when you’re on your period?'],
  ['CoupleDirty', 'female', 'truth', 2, 'Do you mind the taste when you go down on someone?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Does body count matter to you?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Would you ever go to a strip club?'],
  ['CoupleDirty', 'female', 'truth', 2, 'Have you ever tried to stick something that’s not a sex toy into your vagina?'],
  ['CoupleDirty', 'both', 'truth', 2, 'How old were you when you masturbated for the first time?'],
  ['CoupleDirty', 'female', 'truth', 2, 'Do you get turned on by nipple play?'],
  ['CoupleDirty', 'female', 'truth', 2, 'Have you ever had sex on your period?'],
  ['CoupleDirty', 'female', 'truth', 2, 'Do you enjoy having sex on your period?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Which position is your least favorite and why?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Which position is your favorite and why?'],
  ['CoupleDirty', 'female', 'truth', 2, 'Do you enjoy anal play?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What time of day do you prefer to have sex during?'],
  ['CoupleDirty', 'female', 'dare', 2, 'Take off your bra with one hand and without taking off your shirt.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Put an object in your pants and act like it’s your junk.'],
  ['CoupleDirty', 'female', 'dare', 2, 'Wear your bra on your head like a hat for the rest of the game.'],
  ['CoupleDirty', 'female', 'dare', 2, 'Post a pCoupleDirtyo of a tampon on social media and don’t take it down until your next turn.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Practice a sexy dance on a piece of furniture in the room.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Shave part of your eyebrow.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Dye part of your hair a daring color.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Fake an orgasm for 20 seconds.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Do a sexy crawl towards someone else in the room.'],
  ['CoupleDirty', 'both', 'dare', 2, 'Pretend to be any animal in a sexy way.'],
  ['CoupleDirty', 'female', 'dare', 2, 'Redress yourself in a guy’s clothing.'],
  ['CoupleDirty', 'male', 'dare', 2, 'Give a tutorial with an object in the room on how to pleasure a woman.'],
  ['CoupleDirty', 'female', 'dare', 2, 'Imitate how a guy flirts for 20 seconds.'],
  ['CoupleDirty', 'male', 'truth', 2, 'Where’s the most embarrassing place you’ve ever gotten a boner?'],
  ['CoupleDirty', 'female', 'truth', 2, 'What’s the CoupleDirtytest body part on a girl?'],
  ['CoupleDirty', 'male', 'truth', 2, 'What’s the CoupleDirtytest body part on a guy?'],
  ['CoupleDirty', 'female', 'truth', 2, 'Which male celebrity is the CoupleDirtytest in your opinion?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Which celebrity would you do in an instant if you had the chance?'],
  ['CoupleDirty', 'both', 'truth', 2, 'When’s the last time you cried?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What break-up broke your heart the most?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the craziest sex you’ve ever had?'],
  ['CoupleDirty', 'male', 'truth', 2, 'Have you ever gotten head while driving?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Do you find lingerie CoupleDirty?'],,
  ['CoupleDirty', 'both', 'truth', 2, 'How old were you when you had your wet dream?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Do you like to go all night or lay it all out in one fail swoop?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you saved nudes from old hookups or exes?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Do you like sending nudes?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Does body count matter to you on your partners end?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s your favorite position and why?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What time of day is your favorite to have sex during?'],
  ['CoupleDirty', 'male', 'truth', 2, 'Have you ever gotten blue balls?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the strangest thing you’ve ever gotten aroused from?'],
  ['CoupleDirty', 'male', 'truth', 2, 'Have you ever owned or used a blow up doll?'],
  ['CoupleDirty', 'female', 'truth', 2, 'Have you ever worn a sexy piece of clothing?'],
  ['CoupleDirty', 'both', 'truth', 2, 'What’s the most romantic date you’ve ever been on?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Have you ever tried to go down on yourself?'],
  ['CoupleDirty', 'both', 'truth', 2, 'Eat a snack in the sexiest way possible.'],
  ['CoupleDirty', 'both', 'truth', 2, 'Act out your favorite position with objects in the house.'],
  ['CoupleDirty', 'both', 'truth', 2, 'Demonstrate putting on a condom using a household object or food.'],
  ['CoupleDirty', 'male', 'truth', 2, 'Put something in your shirt and pretend to have boobs until the next round is over.'],
  ['CoupleDirty', 'both', 'truth', 2, 'Dye your hair a crazy color.'],
  ['CoupleDirty', 'male', 'truth', 2, 'Spank yourself while calling yourself a “bad boy” for 20 seconds.'],
  ['CoupleDirty', 'female', 'truth', 2, 'Give your best impression of a sexy school girl.'],
  ['CoupleDirty', 'both', 'truth', 3, 'Can you ever watch your partner have sex with someone else?'],
  ['CoupleDirty', 'both', 'truth', 3, 'Are you in love with your partner?'],
  ['CoupleDirty', 'both', 'truth', 3, 'What was your first sexual impression on your partner?'],
  ['CoupleDirty', 'both', 'truth', 3, 'Did you first have lust or love for your partner?'],
  ['CoupleDirty', 'both', 'truth', 3, 'Would you ever get bored of having sex with your partner?'],
  ['CoupleDirty', 'both', 'truth', 3, 'Do you have a friend you’re attracted to?'],
  ['CoupleDirty', 'both', 'truth', 3, 'How many days a week will you have sex?'],
  ['CoupleDirty', 'both', 'truth', 3, 'Who is your partner’s least attractive friend?'],
  ['CoupleDirty', 'both', 'truth', 3, 'Who is your partner’s most attractive friend?'],
  ['CoupleDirty', 'both', 'truth', 3, 'What is your partner’s most annoying sexual habit?'],
  ['CoupleDirty', 'both', 'truth', 3, 'What is your partner’s sweetest trait during sex?'],
  ['CoupleDirty', 'both', 'truth', 3, 'What is your favorite body part of your partner?'],
  ['CoupleDirty', 'both', 'dare', 3, 'Kiss your favorite part on your partner’s body.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Sing you and your partner’s favorite song.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Do an impression of your partner.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Put a strawberry in your mouth and eat it with your partner.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Say something sexual in code that only your partner will understand.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Tell your partner something that will turn them on'],
  ['CoupleDirty', 'both', 'dare', 3, 'Take off your partner’s shirt only with your teeth.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Try not to look at your partner for 2 minutes.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Give your partner an Eskimo kiss.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Do an impression of your partner’s best friend.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Turn on your partner without touching them.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Be your partner’s slave for five minutes.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Lick syrup off your partner’s best body part.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Make out with your partner until the next round.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Brush your partner’s teeth.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Sit on your partner’s lap until the next round.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Make a one minute song about your partner.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Give your partner a foot massage.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Switch underwear with your partner.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Strip in front of your partner.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Smack your partner’s booty.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Suck your partner’s toes for one minute.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Eat strawberry from your partner’s underwear.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Call your partner’s ex.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Bite your partner’s bottom lip.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Go through your partner’s cell phone.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Massage your partner’s back.'],
  ['CoupleDirty', 'both', 'truth', 3, 'When was the first time you were attracted to me?'],
  ['CoupleDirty', 'both', 'truth', 3, 'Have you ever wanted to try tying me down to the bed?'],
  ['CoupleDirty', 'both', 'truth', 3, 'What’s the dirtiest thing you’ve ever imagined doing to me?'],
  ['CoupleDirty', 'both', 'dare', 3, 'Give your spouse your phone for two minutes to do what they want.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Your partner has to use a picture of your orgasm face as their lock screen for 24 hours.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Put an ice cube on your partner’s private for one minute.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Take a shot for every time you forget your anniversary.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Take a shot for every time you forget your partner’s birthday.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Whisper anything hot and steamy into your partner’s ear.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Give your partner a full body massage.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Kiss your partner somewhere new 5 seconds for a minute.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Lick whipped cream off your partner stomach.'],
  ['CoupleDirty', 'both', 'dare', 3, 'You have to beg your partner to spank you.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Take a naughty picture with your partner.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Tease your partner a bit.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Give your partner a naughty dance without pants on. '],
  ['CoupleDirty', 'both', 'dare', 3, 'Do a striptease for your partner.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Massage your partner’s neck with your mouth.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Massage your partner’s back with your mouth.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Tell me one secret no one knows about you.'],
  ['CoupleDirty', 'both', 'dare', 3, 'Is there anything you’d like me to do?'],
  ['CoupleDirty', 'both', 'truth', 3, 'Have you ever pictured me naked?'],
  ['CoupleDirty', 'female', 'dare', 3, 'Suck on my fingers and pretend you’re doing oral.'],

];
