// prettier-ignore
export const CoupleNormal = [
  ['CoupleNormal', 'both', 'truth', 2, 'Did you ever fart inside an elevator?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Did you ever pick your nose in office?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Which is your favorite song to hum in the shower?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Your worst addiction?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Have you ever peed while playing on the beach?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Have you ever lied to your partner?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Narrate your first breakup story giving all details.'],
  ['CoupleNormal', 'both', 'truth', 3, 'What’s your biggest turn off in a person of the opposite sex?'],
  ['CoupleNormal', 'both', 'truth', 2, 'What turns you on?'],
  ['CoupleNormal', 'both', 'truth', 2, 'How far did you go on your first date?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Did you ever taste your pet’s food?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Ever used a cheesy pickup line on your fitness trainer?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Have you ever cursed your partner’s family?'],
  ['CoupleNormal', 'both', 'truth', 2, 'What is the craziest thing on your bucket list?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Which part of your body gets the most compliments? And by whom?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Which actor would you swap your life with for 10 days?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Describe your idea of a horrible date.'],
  ['CoupleNormal', 'both', 'truth', 1, 'Who was your crush in school?'],
  ['CoupleNormal', 'both', 'truth', 2, 'What makes you cry and jump in joy at the same time?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Did you ever have a crush on a high school teacher?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Do you like your partner’s cooking?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Beaches or mountains?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Did you ever dance intimately with someone?'],
  ['CoupleNormal', 'both', 'truth', 1, 'What is the worst gift you have ever received from your partner?'],
  ['CoupleNormal', 'both', 'truth', 2, 'How many kids are you planning to have?'],
  ['CoupleNormal', 'both', 'truth', 2, 'What, in your opinion, is something I must change about myself?'],
  ['CoupleNormal', 'both', 'truth', 1, 'What is your biggest fear about relationships?'],
  ['CoupleNormal', 'both', 'truth', 2, 'What were your exact thoughts while saying, “I do” ?'],
  ['CoupleNormal', 'both', 'truth', 2, 'What is one of the most terrific things that we did together?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Rate our love story on a scale of 1 to 10?'],
  ['CoupleNormal', 'both', 'truth', 1, 'What is your favorite thing to do together?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Are you possessive about me or our relationship?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Partying at a club or a movie night at home?'],
  ['CoupleNormal', 'both', 'truth', 2, 'What is your idea of a perfect couples’ holiday?'],
  ['CoupleNormal', 'both', 'truth', 1, 'What is your favorite time of the year?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Would you ever want to undergo plastic surgery? Why?'],
  ['CoupleNormal', 'both', 'truth', 2, 'What is the biggest insecurity about our relationship?'],
  ['CoupleNormal', 'both', 'truth', 2, 'How would you spend an entire week without me?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Which is your favorite color on me?'],
  ['CoupleNormal', 'both', 'truth', 2, 'What would you enjoy about being stranded with me on a deserted island?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Did you ever two-time while being in a committed relationship?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Have you ever tried skinny dipping in a public pool?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Do you have the hots for someone at your workplace?'],
  ['CoupleNormal', 'both', 'truth', 1, 'At which age did you have your first kiss and with whom?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Did you ever make out in a public library?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Did you ever stalk your ex?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Do you prefer a masseuse of the opposite gender or the same?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Tell something you were always afraid to express.'],
  ['CoupleNormal', 'both', 'truth', 2, 'Will you allow me to check the browsing history on your mobile?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Ever dated someone older than you?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Were you ever attracted to someone from the same gender?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Have you ever had a crush on your best friend’s spouse?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Have you ever burped while kissing someone?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Who is hotter? Me or you?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Did you ever accidentally send a wrong intimate message to your colleague?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Did you ever break up with an ex right before their birthday to avoid buying them a birthday gift?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Did you ever start a rumor about someone you hate?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Did you ever visit a strip club?'],
  ['CoupleNormal', 'both', 'truth', 2, 'If you could win a thousand dollars, would you give up watching your favorite Netflix series?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Did you, at any time, feel uncomfortable in the presence of your parents? When?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Did someone ever break your heart? Who? (I’ll break their bones)'],
  ['CoupleNormal', 'both', 'truth', 3, 'Is there something that you love a lot, but you sacrificed just for me?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Do you have a favorite in-law? Who is he/she?'],
  ['CoupleNormal', 'both', 'truth', 3, 'What is one thing that makes you regret our relationship?'],
  ['CoupleNormal', 'both', 'truth', 3, 'What am I worth exchanging with?'],
  ['CoupleNormal', 'both', 'truth', 1, 'What is one household chore that you hate to do?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Did you ever lie about your GPA?'],
  ['CoupleNormal', 'both', 'truth', 2, 'How many serious relationships have you had?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Did you ever have a tinder profile?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Were you ever on a blind date?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Which animal comes to your mind when you think of me?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Is there a nickname I gave, which you absolutely hate?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Rate the style of my dressing on a scale of 1 to 10.'],
  ['CoupleNormal', 'both', 'truth', 2, 'Name one thing that you just can’t give up even for me.'],
  ['CoupleNormal', 'both', 'truth', 2, 'Do you believe in love at first sight?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Do you prefer a masseuse of the opposite gender or the same?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Will you allow me to check the browsing history on your mobile?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Ever dated someone older than you?'],
  ['CoupleNormal', 'both', 'truth', 2, 'What is your idea of a perfect marriage?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Does the scent of my perfume arouse you?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Share one thing which you think could cause our break up.'],
  ['CoupleNormal', 'both', 'truth', 2, 'Which of my friends do you like to talk to and whom do you hate?'],
  ['CoupleNormal', 'both', 'truth', 3, 'What was the first ever lie you told me?'],
  ['CoupleNormal', 'both', 'truth', 2, 'When you suddenly hear my name in public, what is that one thing which comes to your mind?'],
  ['CoupleNormal', 'both', 'truth', 2, 'What could be your alternate career?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Do you like giving or receiving a lap dance?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Have you ever sent an inappropriate selfie to your ex?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Describe your favorite clothing style.'],
  ['CoupleNormal', 'both', 'truth', 1, 'What kind of food turns you on?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Describe your first intimate experience.'],
  ['CoupleNormal', 'both', 'truth', 2, 'What is that one change you have noticed after marriage?'],
  ['CoupleNormal', 'both', 'truth', 3, 'What is one thing about our physical intimacy that you miss when I’m not around?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Did you ever share a chewing gum with someone?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Do you enjoy PDA?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Which is the most embarrassing show you are guilty of watching?'],
  ['CoupleNormal', 'both', 'truth', 2, 'Did you ever get involved in doing something illegal?'],
  ['CoupleNormal', 'both', 'truth', 1, 'Name two of your guilty pleasures.'],
  ['CoupleNormal', 'both', 'truth', 3, 'What is something disgusting, but you still like doing?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Fierce or fiesty, what defines you in bed?'],
  ['CoupleNormal', 'both', 'truth', 3, 'Would you mind satisfying somebody for money?'],
  ['CoupleNormal', 'both', 'truth', 2, 'How perfect am I as your partner?'],
  ['CoupleNormal', 'both', 'truth', 2, 'When was the longest time you have stayed in a bathroom and why?'],
  ['CoupleNormal', 'both', 'dare', 1, 'Brush your teeth with apple cider vinegar.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Dip a marshmallow in soya sauce and eat it.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Open the backyard door and bark like a dog for 30 seconds.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Open your Instagram or Facebook and like each post of your ex.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Call an Italian restaurant and order sushi.'],
  ['CoupleNormal', 'both', 'dare', 2, 'For the next 5 minutes, talk only in a whispering tone.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Slowly eat a spoonful of cinnamon powder.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Use toothpaste to wash your hands.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Call your colleague and yell liar in the phone, three times.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Pretend you have won a Grammy and give an acceptance speech.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Lick your dog’s ear.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Read the newspaper in a romantic style.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Call up pizza guys and ask if they have formula milk.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Call your best friend and ask if he/she has stolen your watch.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Jump like a frog for 2 minutes.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Re-enact your favorite romantic scene.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Without using any music, sing and dance to any beat.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Sit like a chair against a wall for 2 minutes.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Using cloves of garlic apply a lip balm or a lipstick.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Pretend the mop is your guitar, give a stage show performance.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Call an old friend and talk gibberish.'],
  ['CoupleNormal', 'both', 'dare', 2, 'For a minute, pretend to walk on a ramp and pout for cameras.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Eat a cookie without using your hands.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Mix peanut butter with chili sauce spread it on a slice of bread and eat it.'],
  ['CoupleNormal', 'both', 'dare', 3, 'In the living room, land your imaginary spacecraft and talk like an alien.'],
  ['CoupleNormal', 'male', 'dare', 2, 'Go shirtless and pound like a gorilla on your chest, for one whole minute.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Talk to Siri for a minute without any interruption.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Sing a lullaby beatboxing.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Impersonate your favorite in-law.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Eat like a monkey for a minute.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Eat 10 cookies in one minute.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Record a video of you eating Chinese with chopsticks and share it with your friends.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Close your eyes and floss the teeth.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Whisper one of your darkest secrets.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Play a baby crying video on YouTube and dirty dance on the music of it, till the end of the video.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Open and shut the fridge 16 times, in 16 stylish ways.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Doodle the best possible image of your boss and post it on Twitter without giving any other details.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Eat a bowl of spaghetti using your fingers.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Change your Facebook profile photo to an ugly selfie.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Take a screenshot of your browsing history, print it and paste it on the bathroom mirror.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Change the status of your Facebook profile to “feeling sad”.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Make an account on a dating app and write a crazy bio.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Write a 10-line naughty story and share it with your friends on the Whatsapp group.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Send a weird GIF to the 10th person on your contacts list.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Imitate any five emojis.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Perform a stand-up comedy.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Act like a crying toddler for 4 minutes.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Place ice cubes on your palm and close your fist. Hold it till they all melt.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Cut a few onions and narrate a funny story while cutting them.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Strike up a funny conversation with your parents and hang up abruptly.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Dance with your dog for 3 minutes.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Dig into the trash can and name any three things you have picked.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Text a poor joke to your parents.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Use a voice changing filter and send a funny voice message to your ex.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Talk to a chair as if it’s your celebrity crush.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Row an imaginary boat for one minute.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Reveal what is inside your bag. Every small detail.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Tell 5 of your favorite quotes in one single breath.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Juggle 3 eggs without breaking them.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Dress up like a pop star and sing a romantic song dedicated to our relationship.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Get down on one knee and propose to me.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Say I love you while doing 20 jumping jacks.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Cook a delicious meal in less than 40 minutes.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Plank for 30 seconds and while doing it say one thing you love about me.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Stuff your mouth with marshmallows(or anything) and describe why you love me.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Blindfold and make me a sandwich.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Freestyle rap about our relationship.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Stand on one leg and say any two things that you hate about our relationship.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Go live on any social media account and declare your love for me.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Give me a relaxing foot massage.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Express your love in sign language.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Write a short poem about our love story and sing it.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Do the best couple yoga pose.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Recreate the wedding photos.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Do the laundry for entire next week.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Give me a piggyback ride for 1 whole minute.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Do 5 squats in the slowest manner possible.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Wear your dress inside for next 5 minutes.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Narrate a fake romantic and intimate story about a date with your celebrity crush.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Twerk at a boring song, till the music stops.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Dance on an imaginary pole.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Unwrap a candy with just your teeth.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Belly dance with something from the kitchen as a prop.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Allow being tickled when you are blindfolded.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Draw the alphabet in the air with your lips.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Send a dirty text using only emojis to your best friend.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Eat a cup cake in the nastiest way possible.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Cross-dress and click 10 pictures. Share the pictures with your best friends.'],
  ['CoupleNormal', 'both', 'dare', 3, 'Prank call an ex and say something dirty.'],
  ['CoupleNormal', 'both', 'dare', 1, 'Hug and kiss a cushion or a pillow.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Vacuum the house wearing only pajamas.'],
  ['CoupleNormal', 'both', 'dare', 2, 'Spank yourself 5 times.'],
];
