// prettier-ignore
export const Hot = [
  ['Hot', 'both', 'truth', 2, 'If you had to make out with anyone in this room, who would it be and why?'],
  ['Hot', 'both', 'truth', 2, 'Play “fuck, marry, kill” with three people in the room.'],
  ['Hot', 'both', 'truth', 2, 'Where is the craziest place you’ve ever had sex?'],
  ['Hot', 'both', 'truth', 2, 'Tell the group about a sexual fantasy you have.'],
  ['Hot', 'both', 'truth', 2, 'Who was the worst you’ve ever had and the best you’ve ever had?'],
  ['Hot', 'both', 'truth', 2, 'Read us your best sexting line in a sexy accent.'],
  ['Hot', 'both', 'truth', 2, 'What’s the kinkiest thing you’ve ever done in bed?'],
  ['Hot', 'both', 'truth', 2, 'What’s the most adventurous thing you want to try in bed?'],
  ['Hot', 'both', 'truth', 2, 'Would you rather have sex with someone 20 years older or 20 years younger?'],
  ['Hot', 'both', 'truth', 2, 'What’s the biggest lie you’ve told someone to get them into bed with you?'],
  ['Hot', 'both', 'truth', 2, 'How old were you when you lost your virginity and how did it go?'],
  ['Hot', 'both', 'truth', 2, 'Who was your first kiss?'],
  ['Hot', 'both', 'truth', 2, 'What’s a popular fetish that you would never want to try?'],
  ['Hot', 'both', 'truth', 2, 'Do you remember the first time you experienced an orgasm? Tell us about it.'],
  ['Hot', 'both', 'truth', 2, 'What’s your favorite body part on your body?'],
  ['Hot', 'both', 'truth', 2, 'If you could have one sexual superpower, what would it be?'],
  ['Hot', 'both', 'truth', 2, 'Would you sleep with your boss if you could?'],
  ['Hot', 'both', 'truth', 2, 'What’s the least amount of time you’ve gone between having sex with two different people?'],
  ['Hot', 'both', 'truth', 2, 'What’s the most amount of people you’ve kissed in one night?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever been tempted to cheat on your significant other?'],
  ['Hot', 'both', 'truth', 2, 'What’s your body count?'],
  ['Hot', 'both', 'truth', 2, 'What’s your favorite position?'],
  ['Hot', 'both', 'truth', 2, 'What’s the smallest amount of time you’ve known someone before sleeping with them?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever been caught having sex?'],
  ['Hot', 'both', 'truth', 2, 'What position is popular that you think is overrated?'],
  ['Hot', 'both', 'truth', 2, 'Do you prefer sex when you’re in love or when it’s a hot hookup?'],
  ['Hot', 'both', 'truth', 2, 'Do you think virginity is special?'],
  ['Hot', 'both', 'truth', 2, 'Who is the oddest person you’ve ever had a sexual fantasy about?'],
  ['Hot', 'both', 'truth', 2, 'Do you think there’s an age where someone becomes “too old” to be a virgin?'],
  ['Hot', 'both', 'truth', 2, 'Who in the room do you think has slept with the most people?'],
  ['Hot', 'both', 'truth', 2, 'Do you think there should be a limit on the amount of people you sleep with in your lifetime or do you think that doesn’t matter?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever had sex and immediately gotten up and left?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever called someone “Daddy” or been called “Daddy” while having sex?'],
  ['Hot', 'both', 'truth', 2, 'What do you wish you had learned about sex way earlier than you did?'],
  ['Hot', 'both', 'truth', 2, 'What fictional character have you or could you have sexual fantasies about?'],
  ['Hot', 'both', 'dare', 2, 'Message something bold to someone hot you’ve been wanting to get to know.'],
  ['Hot', 'both', 'dare', 2, 'Kiss someone in the room that you’re attracted to.'],
  ['Hot', 'both', 'dare', 3, 'Fake your best orgasm in front of the group.'],
  ['Hot', 'both', 'dare', 2, 'Leave a sexy voicemail for your ex to listen to.'],
  ['Hot', 'both', 'dare', 3, 'Pick a position and imitate it with the person to your right.'],
  ['Hot', 'both', 'dare', 2, 'Sexily lick the food of your choice off the finger of the person to your left.'],
  ['Hot', 'both', 'dare', 2, 'Find a position online that you’ve never tried and act it out on furniture that’s in the room.'],
  ['Hot', 'both', 'dare', 2, 'Prank call someone and pretend to be a sex ad.'],
  ['Hot', 'both', 'dare', 3, 'Trace the lips of someone here and whisper something sexy.'],
  ['Hot', 'both', 'dare', 2, 'Do a mini strip tease by taking off some of your clothing in front of the group.'],
  ['Hot', 'both', 'dare', 3, 'For the next round, you have to keep your hand on the inner thigh of the person to your left.'],
  ['Hot', 'both', 'dare', 2, 'Post something raunchy on your preferred social media app and you can’t remove it until the next round is over.'],
  ['Hot', 'both', 'dare', 2, 'Give someone else in the group a sexy massage while talking dirty.'],
  ['Hot', 'both', 'dare', 3, 'Time to play spin the bottle! Kiss whoever the bottle lands on.'],
  ['Hot', 'both', 'dare', 2, 'Close your eyes while a few members of the group stand across from you. Walk with your hands open until you touch one of them, then kiss them wherever your hand touched.'],
  ['Hot', 'both', 'dare', 3, 'Give the person to your left an eskimo kiss.'],
  ['Hot', 'both', 'dare', 2, 'You’ve been naughty, time to be put in time out on someone’s lap for the next round.'],
  ['Hot', 'both', 'dare', 2, 'Pick something small to sexily feed someone else in the group.'],
  ['Hot', 'both', 'dare', 2, 'Leave the room while everyone in the group pours a shot. When you come back, pick a shot to take. Whoever poured that shot, you have to kiss.'],
  ['Hot', 'both', 'dare', 2, 'Talk in a raunchy accent until your next turn.'],
  ['Hot', 'both', 'dare', 2, 'Scroll blindly through your contacts and whoever you land on, say one sexy thing about them.'],
  ['Hot', 'both', 'dare', 2, 'Give your best impression of a naughty cop who’s trying to arrest someone for being too sexy.'],
  ['Hot', 'both', 'dare', 2, 'Give the person to your right a butterfly kiss.'],
  ['Hot', 'both', 'dare', 2, 'Wink and do your best sexy face for the group.'],
  ['Hot', 'both', 'dare', 2, 'Pretend to have awful sex with the person to your right.'],
  ['Hot', 'both', 'dare', 2, 'Send bold, dirty message to someone you’ve hooked up with before.'],
  ['Hot', 'both', 'dare', 2, 'Call a phone sex line and pretend to have an odd fetish.'],
  ['Hot', 'both', 'dare', 2, 'Take a pen and paper and draw your penis or vagina.'],
  ['Hot', 'both', 'dare', 2, 'Facetime an old hookup. If they pick up, say something raunchy before hanging up.'],
  ['Hot', 'female', 'dare', 2, 'Fake a blowjob on a bottle.'],
  ['Hot', 'both', 'dare', 2, 'Describe your favorite position in detail but without saying what it is. See if the group can guess it!'],
  ['Hot', 'both', 'truth', 2, 'Have you ever had a sexy dream about someone in the room? Tell us what it was like.'],
  ['Hot', 'both', 'truth', 2, 'How many people have you kissed?'],
  ['Hot', 'both', 'truth', 2, 'How many people have you slept with?'],
  ['Hot', 'both', 'truth', 2, 'Would you rather be the person doing the spanking or be spanked yourself?'],
  ['Hot', 'both', 'truth', 2, 'What’s a position you want to try?'],
  ['Hot', 'both', 'truth', 2, 'Do you have anything you fear sexually?'],
  ['Hot', 'both', 'truth', 2, 'How often do you pleasure yourself a week?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever watched porn? What’s your go-to category?'],
  ['Hot', 'both', 'truth', 2, 'Where is the craziest place you’ve ever masturbated?'],
  ['Hot', 'both', 'truth', 2, 'Where is the craziest place you’ve ever had sex?'],
  ['Hot', 'both', 'truth', 2, 'What’s an odd fetish that you would try out?'],
  ['Hot', 'both', 'truth', 2, 'What’s the record amount of times you’ve had sex in one day?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever had sex while other people were in the room without them knowing?'],
  ['Hot', 'both', 'truth', 2, 'Are you a fan of foreplay?'],
  ['Hot', 'both', 'truth', 2, 'Are you a fan of shower sex?'],
  ['Hot', 'both', 'truth', 2, 'When’s the last time you pleasured yourself?'],
  ['Hot', 'both', 'truth', 2, 'Do you enjoy receiving nudes?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever been to a strip club? If not, would you like to go?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever wanted to try role play?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever masturbated with something weird?'],
  ['Hot', 'both', 'truth', 2, 'How old were you when you first watched porn?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever wanted to try bondage?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever received a lap dance?'],
  ['Hot', 'both', 'truth', 2, 'What’s your favorite fantasy to pleasure yourself to?'],
  ['Hot', 'both', 'truth', 2, 'What sex act have you done that you never want to do again?'],
  ['Hot', 'both', 'truth', 2, 'Tell us about the best orgasm you’ve ever had.'],,
  ['Hot', 'both', 'truth', 2, 'If you woke up as the opposite sex, what’s the first thing you would explore about yourself.'],
  ['Hot', 'both', 'truth', 2, 'Do you like listening to music while having sex?'],
  ['Hot', 'both', 'truth', 2, 'What’s the longest you’ve gone without having sex?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever thought about experimenting with someone of the same sex?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever watched or wanted to watch another couple have sex?'],
  ['Hot', 'both', 'truth', 2, 'Lights off or lights on during sex?'],
  ['Hot', 'both', 'truth', 2, 'Where is your favorite place to have sex?'],
  ['Hot', 'both', 'truth', 2, 'Does dirty talk get you horny?'],
  ['Hot', 'both', 'truth', 2, 'Would you rather give or receive pleasure?'],
  ['Hot', 'both', 'truth', 2, 'What’s a sexual act that you never want to try?'],
  ['Hot', 'both', 'truth', 2, 'What’s the dirtiest thing you’ve ever been caught doing or almost been caught doing?'],
  ['Hot', 'both', 'truth', 2, 'What’s something you’ve fantasized about your partner that’s made you finish when pleasuring yourself before?'],
  ['Hot', 'both', 'truth', 2, 'Do you like sex to be rough or sensual?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever been friend-zoned?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever paid for porn or sexual pleasure in any way?'],
  ['Hot', 'both', 'truth', 2, 'What’s the quickest way to get you into bed?'],
  ['Hot', 'both', 'truth', 2, 'Do you prefer a little hair or smooth-shaven down there?'],
  ['Hot', 'both', 'dare', 2, 'Wear handcuffs or have your hands tied for a few turns.'],
  ['Hot', 'both', 'dare', 2, 'Kiss your partner in the sexiest place and sexiest way possible.'],
  ['Hot', 'both', 'dare', 2, 'Undress your partner with one hand.'],
  ['Hot', 'both', 'dare', 2, 'Suck on your partners finger like you’re giving them head.'],
  ['Hot', 'both', 'truth', 2, 'When did you have your first sexual feelings?'],
  ['Hot', 'both', 'truth', 2, 'When was your first sexual experience?'],
  ['Hot', 'both', 'truth', 2, 'What was your craziest sexual experience like?'],
  ['Hot', 'both', 'truth', 2, 'Where is your favorite place to be kissed on your body?'],
  ['Hot', 'both', 'truth', 2, 'What’s the dirtiest thought you’ve ever had?'],
  ['Hot', 'both', 'truth', 2, 'What’s the dirtiest dream you’ve ever had?'],
  ['Hot', 'both', 'truth', 2, 'Where’s the raunchiest place you dream of having sex?'],
  ['Hot', 'both', 'truth', 2, 'Describe to me the best sex you’ve ever had.'],
  ['Hot', 'both', 'truth', 2, 'Have you ever had phone sex before?'],
  ['Hot', 'both', 'truth', 2, 'Who’s the one that got away?'],
  ['Hot', 'both', 'truth', 2, 'Are you turned on right now?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever been tied up before?'],
  ['Hot', 'both', 'truth', 2, 'What is something that is completely off-limits from trying in bed?'],
  ['Hot', 'both', 'truth', 2, 'If you were to give a full body massage, where would you start and end?'],
  ['Hot', 'both', 'truth', 2, 'What was your funniest sexual experience like?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever had sex in public? Would you or would you again?'],
  ['Hot', 'both', 'truth', 2, 'What celebrity would you have sex with if you could?'],
  ['Hot', 'both', 'truth', 2, 'What’s on your mind right now?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever done something that you feel guilty about?'],
  ['Hot', 'both', 'truth', 2, 'Describe your penis or vagina in detail including what it likes, how it likes it, and how horny it is right now.'],
  ['Hot', 'both', 'truth', 2, 'What was your biggest sexual disappointment?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever been sexually rejected?'],
  ['Hot', 'both', 'truth', 2, 'Describe the funniest mistake that’s happened to you while having sex.'],
  ['Hot', 'both', 'truth', 2, 'Do you have a name for your penis or vagina?'],
  ['Hot', 'both', 'truth', 2, 'What’s the hottest thing I can call your penis or vagina when we’re having sex?'],
  ['Hot', 'both', 'truth', 2, 'Do you own any sex toys?'],
  ['Hot', 'both', 'truth', 2, 'What kinds of sex toys would you want to try?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever kissed someone of the same gender?'],
  ['Hot', 'female', 'truth', 2, 'Have you ever flashed someone?'],
  ['Hot', 'both', 'truth', 2, 'How long do you normally last in bed?'],
  ['Hot', 'both', 'truth', 2, 'Do you like sexting?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever thought about me naked while talking to me?'],
  ['Hot', 'both', 'truth', 2, 'What automatically makes you orgasm during sex?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever had or fantasized about an orgy?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever had or fantasized about a threesome?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever taken someone’s virginity?'],
  ['Hot', 'both', 'truth', 2, 'What excites you the most in bed?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever masturbated in public?'],
  ['Hot', 'both', 'truth', 2, 'What’s your wildest sexual fantasy?'],
  ['Hot', 'both', 'truth', 2, 'What dirty secrets are you hiding?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever tried anal sex?'],
  ['Hot', 'both', 'truth', 2, 'Do you like anal?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever done something sexy with food during sex or foreplay?'],
  ['Hot', 'both', 'dare', 2, 'Let your partner pick what profile picture you get to have for the remainder of the evening.'],
  ['Hot', 'both', 'dare', 2, 'Demonstrate how you masturbate on an object in your room.'],
  ['Hot', 'both', 'dare', 2, 'Give a tutorial on your best sexual technique on something in your room.'],
  ['Hot', 'both', 'dare', 2, 'Slap yourself somewhere hot.'],
  ['Hot', 'female', 'dare', 3, 'Change into the hottest outfit you have and pose in it like a model.'],
  ['Hot', 'both', 'dare', 2, 'Sing a song sexily into the camera.'],
  ['Hot', 'both', 'dare', 2, 'Cut off a little bit of your hair.'],
  ['Hot', 'both', 'dare', 2, 'Draw something on your face with marker.'],
  ['Hot', 'both', 'dare', 2, 'Try being sexy while holding your tongue and talking.'],
  ['Hot', 'both', 'truth', 2, 'Describe what it was like the first time someone went down on you.'],
  ['Hot', 'both', 'truth', 2, 'Have you ever touched yourself while having sex?'],
  ['Hot', 'both', 'truth', 2, 'What’s the worst kiss you’ve ever had and why?'],
  ['Hot', 'both', 'truth', 2, 'What’s the best kiss you’ve ever had and why?'],
  ['Hot', 'both', 'truth', 2, 'What’s the most embarrassing wardrobe malfunction you’ve ever had?'],
  ['Hot', 'both', 'truth', 2, 'Have you had any awkward one-night stands?'],
  ['Hot', 'both', 'truth', 2, 'What’s the most romantic date you’ve ever been on?'],
  ['Hot', 'both', 'truth', 2, 'What’s the most thoughtful gift you’ve ever received in a relationship?'],
  ['Hot', 'both', 'truth', 2, 'What’s the most thoughtful gift you’ve ever given in a relationship?'],
  ['Hot', 'both', 'truth', 2, 'What’s the hottest body part on a guy?'],
  ['Hot', 'both', 'truth', 2, 'What’s the hottest body part on a girl?'],
  ['Hot', 'both', 'truth', 2, 'What’s the awkwardest crush you’ve ever had on someone?'],
  ['Hot', 'both', 'truth', 2, 'Describe the sexual encounter you regret the most.'],
  ['Hot', 'both', 'truth', 2, 'What was it like the first time you went down on someone?'],
  ['Hot', 'female', 'truth', 2, 'Spit or swallow?'],
  ['Hot', 'both', 'truth', 2, 'How often do you shave down there?'],
  ['Hot', 'female', 'truth', 2, 'Have you ever gotten a wax down there?'],
  ['Hot', 'both', 'truth', 2, 'If you were going to have a threesome, would you want the third party to be another girl or a guy?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever been to a strip club?'],
  ['Hot', 'both', 'truth', 2, 'What’s something funny that turns you on?'],
  ['Hot', 'female', 'truth', 2, 'Do you get more horny when you’re on your period?'],
  ['Hot', 'both', 'truth', 2, 'Do you mind the taste when you go down on someone?'],
  ['Hot', 'both', 'truth', 2, 'Does body count matter to you?'],
  ['Hot', 'both', 'truth', 2, 'Would you ever go to a strip club?'],
  ['Hot', 'female', 'truth', 2, 'Have you ever tried to stick something that’s not a sex toy into your vagina?'],
  ['Hot', 'both', 'truth', 2, 'How old were you when you masturbated for the first time?'],
  ['Hot', 'female', 'truth', 2, 'Do you get turned on by nipple play?'],
  ['Hot', 'female', 'truth', 2, 'Have you ever had sex on your period?'],
  ['Hot', 'female', 'truth', 2, 'Do you enjoy having sex on your period?'],
  ['Hot', 'both', 'truth', 2, 'Which position is your least favorite and why?'],
  ['Hot', 'both', 'truth', 2, 'Which position is your favorite and why?'],
  ['Hot', 'female', 'truth', 2, 'Do you enjoy anal play?'],
  ['Hot', 'female', 'truth', 2, 'Do you own lingerie?'],
  ['Hot', 'both', 'truth', 2, 'What time of day do you prefer to have sex during?'],
  ['Hot', 'female', 'dare', 2, 'Take off your bra with one hand and without taking off your shirt.'],
  ['Hot', 'male', 'dare', 2, 'Put an object in your pants and act like it’s your junk.'],
  ['Hot', 'both', 'dare', 2, 'Put someone’s underwear on your head.'],
  ['Hot', 'female', 'dare', 2, 'Wear your bra on your head like a hat for the rest of the game.'],
  ['Hot', 'female', 'dare', 2, 'Post a photo of a tampon on social media and don’t take it down until your next turn.'],
  ['Hot', 'both', 'dare', 2, 'Practice a sexy dance on a piece of furniture in the room.'],
  ['Hot', 'both', 'dare', 2, 'Touch tongues with someone else in the room.'],
  ['Hot', 'both', 'dare', 2, 'Shave part of your eyebrow.'],
  ['Hot', 'both', 'dare', 2, 'Dye part of your hair a daring color.'],
  ['Hot', 'female', 'dare', 2, 'Fake an orgasm for 20 seconds.'],
  ['Hot', 'both', 'dare', 2, 'Do a sexy crawl towards someone else in the room.'],
  ['Hot', 'both', 'dare', 2, 'Pretend to be any animal in a sexy way.'],
  ['Hot', 'female', 'dare', 2, 'Redress yourself in a guy’s clothing.'],
  ['Hot', 'male', 'dare', 2, 'Give a tutorial with an object in the room on how to pleasure a woman.'],
  ['Hot', 'female', 'dare', 2, 'Imitate how a guy flirts for 20 seconds and try to pick up someone in the room.'],
  ['Hot', 'both', 'truth', 2, 'Where’s the most embarrassing place you’ve ever gotten a boner?'],
  ['Hot', 'both', 'truth', 2, 'What’s the hottest body part on a girl?'],
  ['Hot', 'both', 'truth', 2, 'What’s the hottest body part on a guy?'],
  ['Hot', 'female', 'truth', 2, 'Which male celebrity is the hottest in your opinion?'],
  ['Hot', 'both', 'truth', 2, 'Which celebrity would you do in an instant if you had the chance?'],
  ['Hot', 'both', 'truth', 2, 'When’s the last time you cried?'],
  ['Hot', 'both', 'truth', 2, 'What break-up broke your hear the most?'],
  ['Hot', 'both', 'truth', 2, 'What’s the craziest sex you’ve ever had?'],
  ['Hot', 'male', 'truth', 2, 'Have you ever gotten head while driving?'],
  ['Hot', 'both', 'truth', 2, 'Do you find lingerie hot?'],
  ['Hot', 'male', 'truth', 2, 'How large is your package?'],
  ['Hot', 'both', 'truth', 2, 'How old were you when you had your wet dream?'],
  ['Hot', 'both', 'truth', 2, 'Do you like to go all night or lay it all out in one fail swoop?'],
  ['Hot', 'both', 'truth', 2, 'Have you saved nudes from old hookups or exes?'],
  ['Hot', 'both', 'truth', 2, 'Do you like sending nudes?'],
  ['Hot', 'male', 'truth', 2, 'Have you ever gotten whiskey dick?'],
  ['Hot', 'both', 'truth', 2, 'Does body count matter to you?'],
  ['Hot', 'both', 'truth', 2, 'Does body count matter to you on your partners end?'],
  ['Hot', 'both', 'truth', 2, 'What’s your favorite position and why?'],
  ['Hot', 'both', 'truth', 2, 'What time of day is your favorite to have sex during?'],
  ['Hot', 'female', 'truth', 2, 'Have you ever tried anal play? Thoughts?'],
  ['Hot', 'female', 'truth', 2, 'Do you own any sex toys or want to own some?'],
  ['Hot', 'male', 'truth', 2, 'Have you ever gotten blue balls?'],
  ['Hot', 'both', 'truth', 2, 'What’s the strangest thing you’ve ever gotten aroused from?'],
  ['Hot', 'male', 'truth', 2, 'Have you ever been to a strip club?'],
  ['Hot', 'male', 'truth', 2, 'Have you ever owned or used a blow up doll?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever worn a sexy piece of clothing?'],
  ['Hot', 'both', 'truth', 2, 'What’s the most romantic date you’ve ever been on?'],
  ['Hot', 'both', 'truth', 2, 'What’s the most thoughtful gift you’ve ever received in a relationship?'],
  ['Hot', 'both', 'truth', 2, 'What’s the most thoughtful gift you’ve ever given in a relationship?'],
  ['Hot', 'male', 'truth', 2, 'Have you ever had sex with a MILF? If not, do you want to?'],
  ['Hot', 'male', 'truth', 2, 'Do you mind the taste when you eat someone out?'],
  ['Hot', 'both', 'truth', 2, 'Have you ever tried to go down on yourself?'],
  ['Hot', 'male', 'truth', 2, 'Do you like it when girls play with your balls?'],
  ['Hot', 'both', 'truth', 2, 'Do you prefer to be shaved or keep it hairy down there?'],
  ['Hot', 'both', 'truth', 2, 'If you were going to have a threesome, would you want the third party to be another girl or a guy?'],
  ['Hot', 'male', 'dare', 2, 'Imitate a girl flirting for 20 seconds and try to pick up someone else in the room.'],
  ['Hot', 'male', 'dare', 2, 'Give a name to your package and explain why you named it how you did.'],
  ['Hot', 'both', 'dare', 2, 'Eat a snack in the sexiest way possible.'],
  ['Hot', 'both', 'dare', 2, 'Act out your favorite position with objects in the house.'],
  ['Hot', 'both', 'dare', 2, 'Demonstrate putting on a condom using a household object or food.'],
  ['Hot', 'both', 'dare', 2, 'Feed someone else in the room without using your hands.'],
  ['Hot', 'male', 'dare', 2, 'Redress yourself in a girls clothing.'],
  ['Hot', 'both', 'dare', 2, 'Try to use makeup properly on your face and see how it turns out.'],
  ['Hot', 'male', 'dare', 2, 'Put something in your shirt and pretend to have boobs until the next round is over.'],
  ['Hot', 'both', 'dare', 2, 'Dye your hair a crazy color.'],
  ['Hot', 'male', 'dare', 2, 'Spank yourself while calling yourself a “bad boy” for 20 seconds.'],
  ['Hot', 'female', 'dare', 2, 'Give your best impression of a sexy school girl.'],
];
