// prettier-ignore
export const TabooKinky = [
  ['TabooKinky', 'both', 'truth', 3, 'What has been your best sexual experience?'],
  ['TabooKinky', 'both', 'truth', 3, 'What was the last time you gave head?'],
  ['TabooKinky', 'both', 'truth', 3, 'What is the longest time you’ve ever given head?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever done a threesome?'],
  ['TabooKinky', 'both', 'truth', 3, 'Would you ever do a threesome?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s your take on sex in groups?'],
  ['TabooKinky', 'both', 'truth', 3, 'Can you ever watch your partner have sex with someone else?'],
  ['TabooKinky', 'both', 'truth', 3, 'How many partners have you had at one time?'],
  ['TabooKinky', 'both', 'truth', 3, 'Give a description of how your orgasm feels.'],
  ['TabooKinky', 'both', 'truth', 3, 'Where’s your favorite place to make out?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever done the backdoor style, and would you?'],
  ['TabooKinky', 'both', 'truth', 3, 'What is the longest time you’ve gone without sex?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you prefer rough or slow sex?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you like to be on top or beneath?'],
  ['TabooKinky', 'both', 'truth', 3, 'What is your favorite sex position?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you prefer anal?'],
  ['TabooKinky', 'both', 'truth', 3, 'What sex position do you dislike?'],
  ['TabooKinky', 'both', 'truth', 3, 'What is your worst sexual experience?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had sex outdoors?'],
  ['TabooKinky', 'both', 'truth', 3, 'What is the strangest place you can ever have sex?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever done oral on a stranger?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever paid someone to have sex with you?'],
  ['TabooKinky', 'both', 'truth', 3, 'Who was your first sexual partner?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever made a sex tape?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you have a favorite porn star?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you have a favorite strip club?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever stripped before?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you like to do it with the light on or off?'],
  ['TabooKinky', 'both', 'truth', 3, 'Does size matter to you?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you like to have music in the background or not?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you like your partner to be silent or loud?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you like a little bit of foreplay?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s your favorite part of foreplay?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever tried role-playing?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you have a sweet spot?'],
  ['TabooKinky', 'both', 'truth', 3, 'What is your weirdest sexual fantasy?'],
  ['TabooKinky', 'both', 'truth', 3, 'Would you ever have sex with someone for money?'],
  ['TabooKinky', 'both', 'truth', 3, 'Are you flexible in bed?'],
  ['TabooKinky', 'both', 'truth', 3, 'What is the highest number of orgasms you’ve had in one sexual encounter?'],
  ['TabooKinky', 'both', 'truth', 3, 'Would you spit out or swallow?'],
  ['TabooKinky', 'both', 'dare', 3, 'Do a striptease in front of everyone and on the table.'],
  ['TabooKinky', 'both', 'dare', 3, 'Tie a cherry stem with only your tongue.'],
  ['TabooKinky', 'both', 'dare', 3, 'Get on your partner and start riding.'],
  ['TabooKinky', 'both', 'dare', 3, 'Take off your clothes and start twerking in your underwear.'],
  ['TabooKinky', 'both', 'dare', 3, 'Lick your partner from their neck all the way to their middle region.'],
  ['TabooKinky', 'both', 'dare', 3, 'Suck on your partner’s belly button for thirty seconds.'],
  ['TabooKinky', 'both', 'dare', 3, 'Suck on your partner’s nipple for a minute.'],
  ['TabooKinky', 'both', 'dare', 3, 'Put a piece of candy in your mouth and unwrap it.'],
  ['TabooKinky', 'both', 'dare', 3, 'Remove your partner’s underwear with only your mouth.'],
  ['TabooKinky', 'both', 'dare', 3, 'Kiss around your partner’s lower region.'],
  ['TabooKinky', 'both', 'dare', 3, 'Place your hand in your partner’s pants for a minute.'],
  ['TabooKinky', 'both', 'dare', 3, 'Kiss one person seated next to you.'],
  ['TabooKinky', 'both', 'dare', 3, 'Sit in your partner’s stuff until the next round. '],
  ['TabooKinky', 'both', 'dare', 3, 'Spoon your partner until the next round.'],
  ['TabooKinky', 'both', 'dare', 3, 'Give your partner a head for one minute.'],
  ['TabooKinky', 'both', 'dare', 3, 'Run an ice cube on your partner’s body for a minute.'],
  ['TabooKinky', 'both', 'dare', 3, 'Bite your partner’s booty.'],
  ['TabooKinky', 'both', 'dare', 3, 'Kiss your partner’s booty.'],
  ['TabooKinky', 'both', 'dare', 3, 'Lick whipped cream off someone’s body part.'],
  ['TabooKinky', 'both', 'dare', 3, 'Take off all your clothing for the rest of the game.'],
  ['TabooKinky', 'both', 'dare', 3, 'Sit naked for the rest of the game of truth.'],
  ['TabooKinky', 'both', 'dare', 3, 'Send a naked selfie to your partner.'],
  ['TabooKinky', 'both', 'dare', 3, 'Make a naughty video with your partner.'],
  ['TabooKinky', 'both', 'dare', 3, 'Kiss your partner’s private.'],
  ['TabooKinky', 'both', 'dare', 3, 'Stand outside naked for one minute.'],
  ['TabooKinky', 'both', 'dare', 3, 'Have sex for only 3 minutes, and you have to stop with the timer stops.'],
  ['TabooKinky', 'both', 'dare', 3, 'Take off your partner’s bra with your teeth.'],
  ['TabooKinky', 'both', 'dare', 3, 'Send a nude to your ex.'],
  ['TabooKinky', 'both', 'dare', 3, 'Wear your partner’s underwear.'],
  ['TabooKinky', 'both', 'dare', 3, 'Give your partner a back rub.'],
  ['TabooKinky', 'both', 'dare', 3, 'Do whatever the next person has always wanted for fifteen minutes.'],
  ['TabooKinky', 'both', 'dare', 3, 'Do what the entire group says for fifteen minutes.'],
  ['TabooKinky', 'both', 'dare', 3, 'Your partner has to rub your inner thighs.'],
  ['TabooKinky', 'both', 'dare', 3, 'Put a hickey on the inner thighs of someone in the group.'],
  ['TabooKinky', 'both', 'dare', 3, 'Give your partner an orgasm in two minutes.'],
  ['TabooKinky', 'both', 'dare', 3, 'Undress and wear the first thing you find in the closet.'],
  ['TabooKinky', 'both', 'truth', 3, 'How many sexual relationships have you been in before?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever thought of sleeping with someone else?'],
  ['TabooKinky', 'both', 'dare', 3, 'Hop into the shower for two minutes.'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you slept with anyone on campus?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s your GPA?'],
  ['TabooKinky', 'both', 'truth', 3, 'What was the craziest thing you did in your freshman year?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever made love with a professor?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever passed out from too much booze?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the craziest thing you did while drinking?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s your dirty little secret?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the craziest place you’ve made love on campus?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you like your roommate sexually?'],
  ['TabooKinky', 'both', 'truth', 3, 'What is your roommate’s best body part?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had sex in your roommate’s bed?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever considered sleeping with a roommate?'],
  ['TabooKinky', 'both', 'truth', 3, 'How many pool parties have you been to so far?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the craziest pool party you’ve been to?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had a threesome?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever hosted a pool party?'],
  ['TabooKinky', 'both', 'truth', 3, 'Did you smoke or drink before you got to college?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever stripped for money?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had sex with your friend’s partner?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had sex for money?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever considered having an orgy?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had an orgy?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever used a sex toy?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the longest sex you’ve had?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the highest amount of shots you’ve had in one night?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever wet your bed when drunk?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the longest you’ve gone without sex?'],
  ['TabooKinky', 'both', 'truth', 3, 'When was the last time you skipped class?'],
  ['TabooKinky', 'both', 'truth', 3, 'How many times have you skipped class?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever woken up to a stranger in bed?'],
  ['TabooKinky', 'both', 'truth', 3, 'How old were you when you started drinking?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever wondered what a professor looked like naked?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever slept with a freshman?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever slept with someone for money?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you slept with a freshman?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever imagined your roommate naked?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever fought with someone you were sexually attracted to?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever fantasized about sleeping with a professor?'],
  ['TabooKinky', 'both', 'dare', 3, 'Run-on the street with your underwear.'],
  ['TabooKinky', 'both', 'dare', 3, 'Give one person to your right a hickey.'],
  ['TabooKinky', 'both', 'dare', 3, 'Slap the next person’s booty.'],
  ['TabooKinky', 'both', 'dare', 3, 'Feed someone a pack of dry noodles.'],
  ['TabooKinky', 'both', 'dare', 3, 'Take a picture of the next person in their underwear.'],
  ['TabooKinky', 'both', 'dare', 3, 'Lick someone’s toe.'],
  ['TabooKinky', 'both', 'dare', 3, 'Eat toilet paper.'],
  ['TabooKinky', 'both', 'dare', 3, 'Twerk on someone.'],
  ['TabooKinky', 'both', 'dare', 3, 'Make a freestyle about everyone in the room.'],
  ['TabooKinky', 'both', 'dare', 3, 'Give someone a lap dance without any clothing on.'],
  ['TabooKinky', 'both', 'dare', 3, 'Make a prank call and say something naughty.'],
  ['TabooKinky', 'both', 'dare', 3, 'Twerk on the floor.'],
  ['TabooKinky', 'both', 'dare', 3, 'Take someone’s shirt off with your teeth.'],
  ['TabooKinky', 'both', 'dare', 3, 'Kiss the next person to you.'],
  ['TabooKinky', 'both', 'dare', 3, 'Eat the first thing you find in the fridge.'],
  ['TabooKinky', 'both', 'dare', 3, 'Give someone head with their underwear on.'],
  ['TabooKinky', 'both', 'dare', 3, 'Someone should give you a sexy dance while you’re blindfolded.'],
  ['TabooKinky', 'both', 'dare', 3, 'Drink an entire beer in 5 minutes.'],
  ['TabooKinky', 'both', 'dare', 3, 'Raise your shirt and play with your nipples'],
  ['TabooKinky', 'both', 'dare', 3, 'Lick someone’s face'],
  ['TabooKinky', 'both', 'dare', 3, 'Walk outside completely naked.'],
  ['TabooKinky', 'both', 'dare', 3, 'Do a striptease with high heels on.'],
  ['TabooKinky', 'both', 'dare', 3, 'Sit in a trash can for ten minutes.'],
  ['TabooKinky', 'both', 'truth', 3, 'If you were to have a threesome with anyone in the room, who would it be?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s your nastiest browsing history?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever sexted anyone before?'],
  ['TabooKinky', 'both', 'truth', 3, 'What sexual adventurous thing have you always wanted someone to do to you?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s an illegal thing you wished was legal?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s your favorite sexual fantasy?'],
  ['TabooKinky', 'both', 'truth', 3, 'When was the first time you came?'],
  ['TabooKinky', 'both', 'truth', 3, 'When was the last time you came so good?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you have a favorite sex toy?'],
  ['TabooKinky', 'both', 'truth', 3, 'Where’s the weirdest place you’ve ever had sex?'],
  ['TabooKinky', 'both', 'truth', 3, 'When was your first kiss with someone?'],
  ['TabooKinky', 'both', 'truth', 3, 'Who has been your best partner so far?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s your favorite body part of the opposite gender?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s your favorite body part on yourself?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever cheated before?'],
  ['TabooKinky', 'both', 'truth', 3, 'How many people have you slept with?'],
  ['TabooKinky', 'both', 'truth', 3, 'Are you jealous of anyone?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you like angry sex?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you like makeup sex?'],
  ['TabooKinky', 'both', 'dare', 3, 'Fake an orgasm in front of everyone.'],
  ['TabooKinky', 'both', 'dare', 3, 'Kiss one person you touch while blindfolded.'],
  ['TabooKinky', 'both', 'dare', 3, 'Leave a sexy voicemail to your ex.'],
  ['TabooKinky', 'both', 'dare', 3, 'Lick peanut butter off someone’s body.'],
  ['TabooKinky', 'both', 'dare', 3, 'Go skinny dipping with someone in the group.'],
  ['TabooKinky', 'both', 'dare', 3, 'Pretend to make a game plan to sleep with someone in the room.'],
  ['TabooKinky', 'both', 'dare', 3, 'Everyone has to feed you and you have to reply with, \"Thank you, Daddy\". '],
  ['TabooKinky', 'both', 'dare', 3, 'You have to do a timeout on someone’s lap.'],
  ['TabooKinky', 'both', 'dare', 3, 'You have to order a sex toy off Amazon.'],
  ['TabooKinky', 'both', 'dare', 3, 'Act out your favorite sex position.'],
  ['TabooKinky', 'both', 'dare', 3, 'You have to undress and take a shot for every piece of clothing you want to keep on.'],
  ['TabooKinky', 'both', 'dare', 3, 'Trace your fingers on someone’s lip and whisper something naughty.'],
  ['TabooKinky', 'both', 'dare', 3, 'Dare someone to change their Facebook status to, \"I’m coming…\".'],
  ['TabooKinky', 'both', 'dare', 3, 'You have to wear a swimming suit for the rest of the night.'],
  ['TabooKinky', 'both', 'dare', 3, 'Give someone a back massage while kissing their back.'],
  ['TabooKinky', 'both', 'dare', 3, 'Place your hand on the inner thigh of the person next to you.'],
  ['TabooKinky', 'both', 'truth', 3, 'How many exes do you have?'],
  ['TabooKinky', 'both', 'truth', 3, 'How many people have you kissed?'],
  ['TabooKinky', 'both', 'truth', 3, 'How many people have you had sex with?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever been so turned on that you couldn’t control it?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever touched yourself?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had sex at work?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you like being in control in bed?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you prefer being controlled in bed?'],
  ['TabooKinky', 'both', 'truth', 3, 'How far have you gone for sex?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the highest number of sexual intercourse you’ve had in a day?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you done it in people’s presence without them realizing it?'],
  ['TabooKinky', 'both', 'truth', 3, 'What kind of foreplay do you like?'],
  ['TabooKinky', 'both', 'truth', 3, 'Would you take a hot shower with me?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever tried to feel someone up when hugging?'],
  ['TabooKinky', 'both', 'truth', 3, 'What got you hot for the first time?'],
  ['TabooKinky', 'both', 'truth', 3, 'What gets you hot every single time?'],
  ['TabooKinky', 'both', 'truth', 3, 'How bad have you always wanted to tear off my clothes?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you watch naughty movies?'],
  ['TabooKinky', 'both', 'truth', 3, 'How bad do you want to pull my hair?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you like being kissed on the neck?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever thought about me when showering?'],
  ['TabooKinky', 'both', 'truth', 3, 'What naughty things do you keep in your nightstand?'],
  ['TabooKinky', 'both', 'dare', 3, 'Wash your crush’s feet.'],
  ['TabooKinky', 'both', 'dare', 3, 'Tickle your crush for a minute.'],
  ['TabooKinky', 'both', 'dare', 3, 'Try your crush on with only sounds and without lights.'],
  ['TabooKinky', 'both', 'dare', 3, 'Get extremely close to your crush and say something dirty to their face.'],
  ['TabooKinky', 'both', 'dare', 3, 'Blow hot and cold air on their neck for one minute.'],
  ['TabooKinky', 'both', 'dare', 3, 'Write out something secret on their back, and they have to guess it right. If they don’t, they’ll do something for you.'],
  ['TabooKinky', 'both', 'dare', 3, 'Dress your crush up in your clothing.'],
  ['TabooKinky', 'both', 'dare', 3, 'Call your parents and tell them you love someone.'],
  ['TabooKinky', 'both', 'dare', 3, 'Call your crush’s parents and tell them you love them.'],
  ['TabooKinky', 'both', 'dare', 3, 'Do a sexy belly dance using only one leg.'],
  ['TabooKinky', 'both', 'dare', 3, 'Fake a British accent.'],
  ['TabooKinky', 'both', 'dare', 3, 'Do whatever the group tells you for one minute.'],
  ['TabooKinky', 'both', 'dare', 3, 'Give everyone a foot massage.'],
  ['TabooKinky', 'both', 'dare', 3, 'Dance to some music without pants on.'],
  ['TabooKinky', 'both', 'dare', 3, 'Take off your bra with your shirt on.'],
  ['TabooKinky', 'both', 'dare', 3, 'Make out with the third person to your right. '],
  ['TabooKinky', 'both', 'truth', 3, 'Whats your favorite piece of clothing?'],
  ['TabooKinky', 'both', 'truth', 3, 'Is your browsing history clean?'],
  ['TabooKinky', 'both', 'truth', 3, 'Are you achieving your goals so far?'],
  ['TabooKinky', 'both', 'truth', 3, 'Did you ever fantasize about someone older than you?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever put anything weird on your body?'],
  ['TabooKinky', 'both', 'truth', 3, 'When was the first time you ever watched porn?'],
  ['TabooKinky', 'both', 'truth', 3, 'When was the last time you watched porn?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s your wildest sexual fantasy?'],
  ['TabooKinky', 'both', 'dare', 3, 'Send your spouse your naked picture.'],
  ['TabooKinky', 'both', 'dare', 3, 'Act a passionate kissing scene from a movie with the player on your right.'],
  ['TabooKinky', 'both', 'truth', 3, 'How did you feel when someone went down on you for the first time?'],
  ['TabooKinky', 'female', 'truth', 3, 'Have you ever been attracted to a girl?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you had a terrible kiss before?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the most fun you’ve had on a date?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever done anything romantic that you’re proud of?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s your favorite male body part?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s your worst wardrobe malfunction?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever felt embarrassed by a crush?'],
  ['TabooKinky', 'both', 'truth', 3, 'What was it like going down on someone for the first time?'],
  ['TabooKinky', 'female', 'truth', 3, 'Have you ever faked an orgasm?'],
  ['TabooKinky', 'both', 'truth', 3, 'How does it taste when you go down on someone?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever regretted a hookup?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever regretted doing anything for love?'],
  ['TabooKinky', 'both', 'truth', 3, 'How often do you trim down there?'],
  ['TabooKinky', 'female', 'truth', 3, 'Have you ever gotten a bikini wax?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had a threesome?'],
  ['TabooKinky', 'both', 'truth', 3, 'Will you ever have a threesome?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you have any fetishes?'],
  ['TabooKinky', 'female', 'truth', 3, 'Have you ever had a sex dream about any guy I know?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever gone to a strip club?'],
  ['TabooKinky', 'female', 'truth', 3, 'Have you ever stripped for cash before?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s your most powerful sexual experience?'],
  ['TabooKinky', 'both', 'truth', 3, 'When did you lose your virginity?'],
  ['TabooKinky', 'female', 'truth', 3, 'Name one thing you’ve wanted to try so bad with a guy?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever has a one night stand?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the weirdest thing that turns you on?'],
  ['TabooKinky', 'both', 'dare', 3, 'Fake an orgasm for thirty seconds.'],
  ['TabooKinky', 'male', 'dare', 3, 'Put some socks in your pants and pretend it’s your penis for a minute.'],
  ['TabooKinky', 'both', 'dare', 3, 'Act out your favorite sex move.'],
  ['TabooKinky', 'both', 'dare', 3, 'Kiss your best friend in the room for thirty seconds.'],
  ['TabooKinky', 'male', 'dare', 3, 'Give any girl a foot massage in the room.'],
  ['TabooKinky', 'both', 'dare', 3, 'Put some ice cubes into someone’s bra for five minutes.'],
  ['TabooKinky', 'female', 'dare', 3, 'Take off your bra for the rest of the night.'],
  ['TabooKinky', 'both', 'dare', 3, 'Draw someone’s face on your belly button.'],
  ['TabooKinky', 'both', 'dare', 3, 'Put a bra on your head for the rest of the night.'],
  ['TabooKinky', 'female', 'dare', 3, 'Take off your pants and put on some heels.'],
  ['TabooKinky', 'both', 'dare', 3, 'Do a sexy dance with a broom. '],
  ['TabooKinky', 'both', 'dare', 3, 'Do jumping jacks for a minute.'],
  ['TabooKinky', 'both', 'dare', 3, 'Touch someone’s tongue with yours.'],
  ['TabooKinky', 'male', 'dare', 3, 'Demonstrate fingering someone.'],
  ['TabooKinky', 'both', 'dare', 3, 'Do 5 squats on the front porch.'],
  ['TabooKinky', 'both', 'dare', 3, 'Wear the first thing you see in the closet.'],
  ['TabooKinky', 'female', 'dare', 3, 'Try to market your favorite naughty toy.'],
  ['TabooKinky', 'both', 'dare', 3, 'Do a sexy crawl on the ground.'],
  ['TabooKinky', 'male', 'truth', 3, 'What’s your favorite body part on a girl?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the most embarrassing moment you got turned on?'],
  ['TabooKinky', 'male', 'truth', 3, 'Have you ever thought of having sex with a guy?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the craziest thing you ever did for love?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever been embarrassed about something you did for love?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had a crush on someone out of your league?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever cheated?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever cried for love?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever made someone cry?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had a threesome?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you had a sex dream about anyone I know?'],
  ['TabooKinky', 'both', 'truth', 3, 'Would you ever have a threesome?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had an orgy?'],
  ['TabooKinky', 'both', 'truth', 3, 'Would you ever have an orgy?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had sex in a car?'],
  ['TabooKinky', 'both', 'truth', 3, 'When did you lose your virginity?'],
  ['TabooKinky', 'both', 'truth', 3, 'What do you wish to try in the bedroom?'],
  ['TabooKinky', 'male', 'truth', 3, 'Have you ever been given head while driving?'],
  ['TabooKinky', 'both', 'truth', 3, 'How do you like lingerie, a little reveal, or no reveal?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever done role play before?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you like second rounds or are they exhausting?'],
  ['TabooKinky', 'male', 'truth', 3, 'What’s the worst lie you’ve ever told a girl?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you have any steamy videos on your phone?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you have any hot photos on your phone?'],
  ['TabooKinky', 'both', 'truth', 3, 'How many people have you seen naked?'],
  ['TabooKinky', 'male', 'truth', 3, 'Mention one thing you’ve wanted to do so bad with a girl?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the craziest sex dream you’ve had?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had a bad experience with alcohol?'],
  ['TabooKinky', 'male', 'dare', 3, 'Act out how to woo a lady.'],
  ['TabooKinky', 'male', 'dare', 3, 'Talk about your penis like it was a person.'],
  ['TabooKinky', 'both', 'dare', 3, 'Reenact sounds from your last sexual encounter.'],
  ['TabooKinky', 'both', 'dare', 3, 'Hit on someone in the group like at a bar.'],
  ['TabooKinky', 'both', 'dare', 3, 'Try to make different possible sounds with your lips.'],
  ['TabooKinky', 'both', 'dare', 3, 'Make different possible fart sounds with your underarm.'],
  ['TabooKinky', 'male', 'dare', 3, 'Explain how to wear a condom using a banana.'],
  ['TabooKinky', 'both', 'dare', 3, 'Put ice cubes in your mouth until they melt.'],
  ['TabooKinky', 'both', 'dare', 3, 'Eat anything in the kitchen as sexily as possible.'],
  ['TabooKinky', 'both', 'dare', 3, 'Tell your best friend some nasty words in his ear.'],
  ['TabooKinky', 'both', 'dare', 3, 'Give someone a foot massage in the room.'],
  ['TabooKinky', 'both', 'dare', 3, 'Act like you’re having sex with the couch for a minute.'],
  ['TabooKinky', 'both', 'dare', 3, 'Read a book in the most seductive way possible.'],
  ['TabooKinky', 'both', 'dare', 3, 'Make out with your hand to a romantic country song.'],
  ['TabooKinky', 'both', 'dare', 3, 'Put on some headphones and dance to your favorite song.'],
  ['TabooKinky', 'both', 'dare', 3, 'You have to hold water in your mouth until the round finishes.'],
  ['TabooKinky', 'both', 'dare', 3, 'Slap your behind and talk about how bad you’ve been.'],
  ['TabooKinky', 'both', 'dare', 3, 'Feed someone some strawberries using only your mouth. '],
  ['TabooKinky', 'both', 'dare', 3, 'Draw something nasty on your face.'],
  ['TabooKinky', 'female', 'dare', 3, 'Grind to your pillow for a minute.'],
  ['TabooKinky', 'both', 'dare', 3, 'Feed someone almond with your mouth.'],
  ['TabooKinky', 'both', 'dare', 3, 'Passionately play an air guitar for one minute.'],
  ['TabooKinky', 'both', 'truth', 3, 'What was the last video you watched on YouTube?'],
  ['TabooKinky', 'both', 'truth', 3, 'What color is your underwear?'],
  ['TabooKinky', 'both', 'truth', 3, 'What are the naughtiest things you’ve ever done so far?'],
  ['TabooKinky', 'both', 'truth', 3, 'Tell everyone anything your mum doesn’t know about you?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s your most embarrassing fart story?'],
  ['TabooKinky', 'both', 'truth', 3, 'What did you want to be when you were little?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the dumbest statement you’ve ever made?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the dumbest statement I’ve made so far?'],
  ['TabooKinky', 'both', 'truth', 3, 'When was your sexual awakening?'],
  ['TabooKinky', 'both', 'truth', 3, 'When was your best sexual experience?'],
  ['TabooKinky', 'both', 'truth', 3, 'When was your first sexual experience?'],
  ['TabooKinky', 'both', 'truth', 3, 'What was your wildest sexual experience?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the most sensual part of your body that you like to be kissed?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the worst thought you’ve had so far?'],
  ['TabooKinky', 'both', 'truth', 3, 'What is the best news you’ve ever gotten?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the naughtiest activity you’ve done at work?'],
  ['TabooKinky', 'both', 'dare', 3, 'Demonstrate your best sexual position with signs.'],
  ['TabooKinky', 'both', 'dare', 3, 'Walk outside in your underwear.'],
  ['TabooKinky', 'both', 'dare', 3, 'Walk outside naked.'],
  ['TabooKinky', 'female', 'dare', 3, 'Change into the hottest outfit you have.'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever cried because of anyone?'],
  ['TabooKinky', 'both', 'truth', 3, 'What is your favorite belonging?'],
  ['TabooKinky', 'both', 'truth', 3, 'What are your major body-part insecurities?'],
  ['TabooKinky', 'both', 'truth', 3, 'What naughty things have been on your mind lately?'],
  ['TabooKinky', 'both', 'truth', 3, 'What naughty things are you thinking about right now?'],
  ['TabooKinky', 'both', 'truth', 3, 'What are your biggest sexual fears?'],
  ['TabooKinky', 'both', 'truth', 3, 'Has there been anyone who got away during sex?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you dyed your pubic hair before?'],
  ['TabooKinky', 'both', 'truth', 3, 'What color are you open to dye your pubic hair to?'],
  ['TabooKinky', 'both', 'truth', 3, 'Are you turned on right now?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you like being tied up?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the number one activity you hate in bed?'],
  ['TabooKinky', 'both', 'truth', 3, 'Where would you like to be massaged?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you have any funny sexual experiences?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had sexual intercourse in public?'],
  ['TabooKinky', 'both', 'truth', 3, 'Would you sleep with any of your exes again?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the hottest thing someone has done to you?'],
  ['TabooKinky', 'both', 'truth', 3, 'Name one activity you wished someone did to you?'],
  ['TabooKinky', 'both', 'dare', 3, 'Put your butt on your phone for thirty seconds.'],
  ['TabooKinky', 'both', 'dare', 3, 'Sing opera.'],
  ['TabooKinky', 'both', 'dare', 3, 'Take off any three items from your body.'],
  ['TabooKinky', 'both', 'dare', 3, 'Draw anything silly on your face.'],
  ['TabooKinky', 'both', 'dare', 3, 'Cut some parts of your hair.'],
  ['TabooKinky', 'both', 'dare', 3, 'Make a silly video in your underwear and post it on Instagram.'],
  ['TabooKinky', 'both', 'dare', 3, 'Make three sensual hand gestures.'],
  ['TabooKinky', 'both', 'dare', 3, 'Read a dirty part from a romance novel.'],
  ['TabooKinky', 'both', 'dare', 3, 'Talk dirty for thirty seconds.'],
  ['TabooKinky', 'both', 'dare', 3, 'Dance dirty to any song on your phone.'],
  ['TabooKinky', 'both', 'dare', 3, 'Show three embarrassing spots on your body.'],
  ['TabooKinky', 'both', 'dare', 3, 'Draw a mustache on your face.'],
  ['TabooKinky', 'both', 'dare', 3, 'Try to recreate a kissing scene from a movie.'],
  ['TabooKinky', 'both', 'dare', 3, 'Demonstrate your favorite sexual position.'],
  ['TabooKinky', 'both', 'dare', 3, 'Pleasure yourself with ice cubes all over your body.'],
  ['TabooKinky', 'both', 'dare', 3, 'Lick your phone screen for ten seconds.'],
  ['TabooKinky', 'both', 'dare', 3, 'Try to act seductive for the next 2 minutes.'],
  ['TabooKinky', 'both', 'dare', 3, 'Try to turn someone on with only your eyes.'],
  ['TabooKinky', 'both', 'dare', 3, 'Eat your favorite snack seductively.'],
  ['TabooKinky', 'both', 'dare', 3, 'Try to juggle any three items.'],
  ['TabooKinky', 'both', 'truth', 3, 'Who is the love of your life?'],
  ['TabooKinky', 'both', 'truth', 3, 'Who used to be the love of your life?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s one naughty secret that most people can never find out about you?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever done something sexual you felt really guilty about?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s one secret only close friends know about?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever had a disappointing sexual experience?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever been turned down sexually?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s that one item you’ve kept since childhood? '],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the most fun object in your bedroom?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the weirdest item in your room right now?'],
  ['TabooKinky', 'both', 'truth', 3, 'The worst sexual mistake you’ve ever made?'],
  ['TabooKinky', 'both', 'truth', 3, 'Where are your favorite romantic places?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever made out with someone of the same gender?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever slept with someone of the same gender?'],
  ['TabooKinky', 'both', 'truth', 3, 'How many adult toys have you had?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you sexted someone before?'],,
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever picked your nose during sex?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the weirdest stuff you do by yourself?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the craziest stuff you do all alone?'],
  ['TabooKinky', 'both', 'truth', 3, 'Who do you currently find extremely attractive?'],
  ['TabooKinky', 'both', 'truth', 3, 'Which one of your friends turns you on the most?'],
  ['TabooKinky', 'both', 'truth', 3, 'Which one of your friends turns you on the least?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever farted during sex?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever took a break during sex?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever grabbed a snack during sex?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever been bored during sex?'],
  ['TabooKinky', 'both', 'truth', 3, 'When was the last time you peed or pooped your pants?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever done anything illegal?'],
  ['TabooKinky', 'both', 'truth', 3, 'What sex act do you wish you could erase from your memory?'],
  ['TabooKinky', 'both', 'dare', 3, 'Show your underarms.'],
  ['TabooKinky', 'both', 'dare', 3, 'Do a funny freestyle about the next person.'],
  ['TabooKinky', 'both', 'dare', 3, 'Give someone access to your dating profile to do what they want for fifteen minutes.'],
  ['TabooKinky', 'both', 'dare', 3, 'Make a sandwich and feed it to someone.'],
  ['TabooKinky', 'both', 'dare', 3, 'Someone picks a hilarious new nickname for you.'],
  ['TabooKinky', 'both', 'dare', 3, 'Call someone on your contact list and tell them you love them.'],
  ['TabooKinky', 'both', 'dare', 3, 'Put an embarrassing picture as your profile picture.'],
  ['TabooKinky', 'both', 'dare', 3, 'Do a fast dance to a slow song.'],
  ['TabooKinky', 'both', 'dare', 3, 'Eat your food without cutlery.'],
  ['TabooKinky', 'both', 'dare', 3, 'Kiss someone’s belly button.'],
  ['TabooKinky', 'both', 'dare', 3, 'Smell someone’s shoe for two minutes. '],
  ['TabooKinky', 'both', 'truth', 3, 'What sexual activity are you never going to do again?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the shortest time you’ve known someone before sleeping with them?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the weirdest sexual fantasy you’ve had about someone?'],
  ['TabooKinky', 'both', 'truth', 3, 'Who’s the weirdest person you’ve had a sexual fantasy about?'],
  ['TabooKinky', 'both', 'truth', 3, 'What sexual activity do you think is overhyped?'],
  ['TabooKinky', 'both', 'truth', 3, 'If you had to choose between oral and penetration forever, which one would you go with?'],
  ['TabooKinky', 'both', 'truth', 3, 'Do you prefer to be in love and be intimate or just strangers?'],
  ['TabooKinky', 'both', 'truth', 3, 'Who’s the oldest person you’ve slept with?'],
  ['TabooKinky', 'both', 'truth', 3, 'Can you remember the full names of everyone you’ve slept with?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s your sexual goal for now?'],
  ['TabooKinky', 'both', 'truth', 3, 'Have you ever slept with a virgin?'],
  ['TabooKinky', 'both', 'truth', 3, 'Would you rather be on top or beneath?'],
  ['TabooKinky', 'both', 'truth', 3, 'Where turns you on, on the opposite gender?'],
  ['TabooKinky', 'both', 'truth', 3, 'What do you like doing in bed, but others dislike it?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the sexiest statement you’ve heard from someone?'],
  ['TabooKinky', 'both', 'truth', 3, 'What’s the most unintentionally least appealing thing you’ve heard from someone?'],
  ['TabooKinky', 'both', 'truth', 3, 'Would you prefer to give unlimited orgasms, or receive?'],
  ['TabooKinky', 'both', 'truth', 3, 'What type of porn have you watched?'],
  ['TabooKinky', 'both', 'truth', 3, 'What age do you think is too old to be a virgin?'],
  ['TabooKinky', 'both', 'truth', 3, 'Name on sexual superpower you wish you had.'],
  ['TabooKinky', 'both', 'truth', 3, 'What character in a movie do you have sexual fantasies about?'],
  ['TabooKinky', 'both', 'dare', 3, 'Sing a song you’ve made love to.'],
  ['TabooKinky', 'both', 'dare', 3, 'Randomly select anybody on your contact and say something hot about them.'],
  ['TabooKinky', 'both', 'dare', 3, 'Send a seductive message to someone on your contact list.'],
  ['TabooKinky', 'both', 'dare', 3, 'Lick another person’s lips and they have to resist kissing back.'],
  ['TabooKinky', 'both', 'dare', 3, 'Talk dirty to someone for two minutes'],
  ['TabooKinky', 'both', 'dare', 3, 'Wear a blindfold and kiss whatever body part is put in front of you.'],
  ['TabooKinky', 'both', 'dare', 3, 'Lick anything sweet off someone’s neck.'],
  ['TabooKinky', 'both', 'dare', 3, 'Take a seductive selfie and send it to someone in the room. '],
  ['TabooKinky', 'both', 'dare', 3, 'Send a seductive message to someone you’ve slept with.'],
  ['TabooKinky', 'both', 'dare', 3, 'Whisper anything to the next person that will turn them on.'],
  ['TabooKinky', 'both', 'dare', 3, 'Undress someone with only one hand.'],
  ['TabooKinky', 'female', 'dare', 3, 'Use an adult toy for 60 seconds.'],
  ['TabooKinky', 'both', 'dare', 3, 'Take off your underwear for the rest of the night.'],
  ['TabooKinky', 'both', 'dare', 3, 'Show everyone the sexiest picture you have on your phone.'],
  ['TabooKinky', 'both', 'dare', 3, 'Put whipped cream on your body, and allow someone to lick it off.'],
  ['TabooKinky', 'both', 'dare', 3, 'Sleep with someone in a room you’ve never done it before.'],
  ['TabooKinky', 'both', 'dare', 3, 'Try to make someone orgasm in five minutes.'],
  ['TabooKinky', 'both', 'dare', 3, 'Kiss someone’s neck for thirty seconds.'],
  ['TabooKinky', 'both', 'dare', 3, 'Try to arouse someone without touching any sensual places.'],
  ['TabooKinky', 'both', 'dare', 3, 'Use your tongue to spell out anything on someone’s body.'],
  ['TabooKinky', 'both', 'dare', 3, 'Kiss someone’s earlobe for thirty seconds.'],
  ['TabooKinky', 'both', 'dare', 3, 'Whisper to someone anything you’ve wanted to do with them.'],
  ['TabooKinky', 'both', 'dare', 3, 'Show everyone the dirtiest message you have on your phone.'],
  ['TabooKinky', 'both', 'dare', 3, 'Perform a motorboat on someone. If you’re a girl, have someone do it to you.'],
];
