// prettier-ignore
export const Teens = [
  ['Teens', 'both', 'truth', 2, 'Who was your first crush at school?'],
  ['Teens', 'male', 'truth', 1, 'Who is the most beautiful girl at school?'],
  ['Teens', 'female', 'truth', 1, 'Who is the most handsome guy at school?'],
  ['Teens', 'both', 'truth', 1, 'What’s your idea of a perfect date?'],
  ['Teens', 'both', 'truth', 1, 'Where would you like to go on a first date?'],
  ['Teens', 'both', 'truth', 1, 'Do you have a boyfriend?'],
  ['Teens', 'both', 'truth', 1, 'How many boyfriends have you had?'],
  ['Teens', 'both', 'truth', 1, 'Have you been kissed yet?'],
  ['Teens', 'both', 'truth', 1, 'When did you have your first kiss, and with who?'],
  ['Teens', 'both', 'truth', 1, 'Did you ever break your boyfriend’s/girlfriend’s heart?'],
  ['Teens', 'both', 'truth', 1, 'Was your heart ever broken by your boyfriend/girlfriend?'],
  ['Teens', 'both', 'truth', 1, 'If you could go out on a date with a celebrity, who would it be?'],
  ['Teens', 'both', 'truth', 1, 'If you are stranded on a remote island, who would you choose for company?'],
  ['Teens', 'both', 'truth', 1, 'If you had to go out on a date with one of us in the room, who would it be?'],
  ['Teens', 'both', 'truth', 1, 'Of all the people you have dated, who has the most beautiful eyes?'],
  ['Teens', 'both', 'truth', 1, 'Tell us about your most embarrassing date?'],
  ['Teens', 'both', 'truth', 1, 'What was your most awkward moment on a date?'],
  ['Teens', 'both', 'truth', 1, 'Who do you think is the most beautiful/handsome teacher at school?'],
  ['Teens', 'both', 'truth', 1, 'Did you ever have a crush on any of your best friend’s boyfriends/girlfriends?'],
  ['Teens', 'both', 'truth', 1, 'Have you ever flirted with your best friend’s siblings?'],
  ['Teens', 'both', 'truth', 1, 'Would you use a dating website?'],
  ['Teens', 'both', 'truth', 1, 'If you had to pick one of us to go on a prom date, who would it be?'],
  ['Teens', 'both', 'truth', 1, 'Are you obsessed with a celebrity?'],
  ['Teens', 'both', 'truth', 1, 'Would you break up with someone by sending them a text?'],
  ['Teens', 'both', 'truth', 1, 'Are you jealous of someone because of who they date?'],
  ['Teens', 'both', 'truth', 1, 'How would you want the love of your life to propose to you?'],
  ['Teens', 'both', 'truth', 1, 'What kind of a person would you want to be married to in the future?'],
  ['Teens', 'both', 'truth', 1, 'Have you ever fallen in love with someone at first sight?'],
  ['Teens', 'both', 'truth', 1, 'Who is your best friend (when the person has two good friends) – name only one?'],
  ['Teens', 'both', 'truth', 1, 'Did you ever lie to your best friend/bud?'],
  ['Teens', 'both', 'truth', 1, 'Did you make them do something for you by lying?'],
  ['Teens', 'both', 'truth', 1, 'What were your first impressions about “best friend’s name”?'],
  ['Teens', 'both', 'truth', 1, 'Would you lie or cheat for a friend?'],
  ['Teens', 'both', 'truth', 1, 'What would you do if you had a crush on your bestie’s boyfriend/girlfriend?'],
  ['Teens', 'both', 'truth', 1, 'Would you go behind your bestie’s back with a crush?'],
  ['Teens', 'both', 'truth', 1, 'Would you ditch a lunch date with your bestie to go on a date?'],
  ['Teens', 'both', 'truth', 1, 'Name one quality that you do not like in your friend.'],
  ['Teens', 'both', 'truth', 1, 'What do you like most about your best friend?'],
  ['Teens', 'both', 'truth', 1, 'What are the three most important qualities you look for in a friend?'],
  ['Teens', 'both', 'truth', 1, 'Who was the worst friend you have had and why?'],
  ['Teens', 'both', 'truth', 1, 'What is the cruelest thing you have done to a friend?'],
  ['Teens', 'both', 'truth', 1, 'Have you ever shared your best friend’s secrets with anyone else?'],
  ['Teens', 'both', 'truth', 1, 'Can you go for weeks or even months without talking to your bestie?'],
  ['Teens', 'both', 'truth', 1, 'Did you have an imaginary friend? What was his or her name?'],
  ['Teens', 'both', 'truth', 1, 'Did you ever cheat in a test?'],
  ['Teens', 'both', 'truth', 1, 'Did you actually enjoy reading a romantic poem in literature class but pretended that it was lame?'],
  ['Teens', 'both', 'truth', 1, 'What’s your career ambition?'],
  ['Teens', 'both', 'truth', 1, 'How confident are you about achieving your dreams?'],
  ['Teens', 'both', 'truth', 1, 'Which subject do you hate the most?'],
  ['Teens', 'both', 'truth', 1, 'Which is the most boring class you had to attend?'],
  ['Teens', 'both', 'truth', 1, 'Did you ever skip school by telling a lie and lie about it to your parents?'],
  ['Teens', 'both', 'truth', 1, 'Did you ever mock a teacher or classmate behind their back?'],
  ['Teens', 'both', 'truth', 1, 'What is the first thing you do after school every day?'],
  ['Teens', 'both', 'truth', 1, 'What is your favorite thing to do at school?'],
  ['Teens', 'both', 'truth', 1, 'Do you like gym class?'],
  ['Teens', 'both', 'truth', 1, 'Are you into sports?'],
  ['Teens', 'both', 'truth', 1, 'Who is your favorite teacher and why?'],
  ['Teens', 'both', 'truth', 1, 'Have you ever played a prank on a teacher?'],
  ['Teens', 'both', 'truth', 1, 'How many times have you been punished and sent to the principal’s office?'],
  ['Teens', 'both', 'truth', 1, 'Who is the creepiest kid you know in school?'],
  ['Teens', 'both', 'truth', 1, 'What is the lowest/worst grade you got in school?'],
  ['Teens', 'both', 'truth', 1, 'Have you ever fallen asleep in class?'],
  ['Teens', 'both', 'truth', 1, 'Did you pretend to be sick so you can skip class or avoid a test?'],
  ['Teens', 'both', 'truth', 1, 'Who was the first boy that you kissed in school?'],
  ['Teens', 'both', 'truth', 1, 'Which college are you planning to go to?'],
  ['Teens', 'both', 'truth', 1, 'What would you do if you cannot get into the college of your choice?'],
  ['Teens', 'both', 'truth', 1, 'If you had the money and resources to start a business, what would it be?'],
  ['Teens', 'both', 'truth', 1, 'If you could invent something, what would it be?'],
  ['Teens', 'both', 'truth', 1, 'If you won a million dollars in lottery, what would you do with the money?'],
  ['Teens', 'both', 'truth', 1, 'If not here, where would you be and what would you be doing at this moment?'],
  ['Teens', 'both', 'truth', 1, 'Who is your role model and why?'],
  ['Teens', 'both', 'truth', 1, 'What’s your dream job?'],
  ['Teens', 'both', 'truth', 1, 'What’s your idea of a perfect vacation?'],
  ['Teens', 'both', 'truth', 1, 'Imagine this: you wake up one day and realize that you’ve become invisible. What will you do?'],
  ['Teens', 'both', 'truth', 1, 'If you had the chance to be reborn as someone in this room, who would it be?'],
  ['Teens', 'both', 'truth', 1, 'If you could be born again, what would you choose to be born as?'],
  ['Teens', 'both', 'truth', 1, 'What is your worst fear?'],
  ['Teens', 'both', 'truth', 1, 'If you had just 24 hr to live, how would you spend your day?'],
  ['Teens', 'both', 'truth', 1, 'If you had the chance to live on your own right now, would you take it?'],
  ['Teens', 'both', 'truth', 1, 'What is the one thing you would change in your life if you had the option?'],
  ['Teens', 'both', 'truth', 1, 'If you had one wish, what would you wish for?'],
  ['Teens', 'both', 'truth', 1, 'If you knew that the world was going to end soon, what would you do?'],
  ['Teens', 'both', 'truth', 1, 'If you were a superhero, what would your power be?'],
  ['Teens', 'both', 'truth', 1, 'Would you rather be a princess or a mermaid?'],
  ['Teens', 'both', 'truth', 1, 'What would you do if you were the Queen of England?'],
  ['Teens', 'both', 'truth', 1, 'Would you become a boy (or girl) for a day, if you had the choice? Why?'],
  ['Teens', 'both', 'truth', 1, 'If your parents went out of town for a week and you had the house to yourself, what would you do?'],
  ['Teens', 'both', 'truth', 1, 'What was the worst day of your life and why?'],
  ['Teens', 'both', 'truth', 1, 'What was the weirdest/strangest dream you have ever had?'],
  ['Teens', 'both', 'truth', 1, 'What is the one question you do not want to be asked in this game? (remember this for later!)'],
  ['Teens', 'both', 'truth', 1, 'Rate everyone in this room, on a scale of one to ten.'],
  ['Teens', 'both', 'truth', 1, 'List five disgusting/annoying habits you have?'],
  ['Teens', 'both', 'truth', 1, 'What is your weight?'],
  ['Teens', 'both', 'truth', 1, 'Have you ever stolen something?'],
  ['Teens', 'both', 'truth', 1, 'Did you let someone else take the fall for something you did?'],
  ['Teens', 'both', 'truth', 1, 'What was your childhood nickname?'],
  ['Teens', 'both', 'truth', 1, 'What is the most embarrassing thing that your parents caught you do?'],
  ['Teens', 'both', 'truth', 1, 'What was the stupidest thing you ever did?'],
  ['Teens', 'both', 'truth', 1, 'How long have you gone without showering/shaving?'],
  ['Teens', 'both', 'truth', 1, 'Did you ever pee in the swimming pool, while swimming?'],
  ['Teens', 'both', 'truth', 1, 'Did you ever spread a nasty rumor about someone else?'],
  ['Teens', 'both', 'truth', 1, 'What’s the weirdest thing you did when you were alone, in front of a mirror?'],
  ['Teens', 'both', 'truth', 1, 'What kind of pajamas do you wear to bed?'],
  ['Teens', 'both', 'truth', 1, 'What is the silliest thing that you are attached to and still posses (if it were a thing)?'],
  ['Teens', 'both', 'truth', 1, 'Did you ever watch an adult film and lie to your parents about it?'],
  ['Teens', 'both', 'truth', 1, 'What was the biggest lie you told without getting caught?'],
  ['Teens', 'both', 'truth', 1, 'If you were asked to make one of the people in this room your slave, who would you choose and why?'],
  ['Teens', 'both', 'truth', 1, 'Who looks sexier: (give two girlfriends’ names)?'],
  ['Teens', 'both', 'truth', 1, 'Name one thing you hate in each of us.'],
  ['Teens', 'both', 'truth', 1, 'Who is the one person you hate most in the world?'],
  ['Teens', 'both', 'truth', 1, 'What do you do when you are alone at home?'],
  ['Teens', 'both', 'dare', 1, 'Kiss the person to your left on the forehead.'],
  ['Teens', 'both', 'dare', 1, 'Go to the kitchen and eat a chili.'],
  ['Teens', 'both', 'dare', 1, 'Sing a song and do the hokey pokey in the center of the circle.'],
  ['Teens', 'both', 'dare', 1, 'Run around the room imitating a monkey or a gorilla.'],
  ['Teens', 'both', 'dare', 1, 'Pick someone from the group and dance with them to a love song.'],
  ['Teens', 'both', 'dare', 1, 'Kiss the pillow until it is your turn again.'],
  ['Teens', 'both', 'dare', 1, 'Wear your socks on your hands for the next three rounds.'],
  ['Teens', 'both', 'dare', 1, 'Paint each fingernail and toenail a different color and keep it for a day.'],
  ['Teens', 'both', 'dare', 1, 'Wear your pants backward for the rest of the evening.'],
  ['Teens', 'both', 'dare', 1, 'Apply makeup without looking into the mirror.'],
  ['Teens', 'both', 'dare', 1, 'Run in your place for the next two rounds.'],
  ['Teens', 'both', 'dare', 1, 'Pretend to be a pig and sniff the others in the group when it is their turn to speak.'],
  ['Teens', 'both', 'dare', 1, 'Paint your toenails with crayons.'],
  ['Teens', 'both', 'dare', 1, 'Gaze into a girl’s or boy’s eyes for 30 seconds.'],
  ['Teens', 'both', 'dare', 1, 'Slow dance to a fast song.'],
  ['Teens', 'both', 'dare', 1, 'Hop like a kangaroo for a minute and cover the entire room.'],
  ['Teens', 'both', 'dare', 1, 'Propose to your pet or the host’s pet in the most romantic way possible.'],
  ['Teens', 'both', 'dare', 1, 'Speak in a foreign accent for the next two minutes.'],
  ['Teens', 'both', 'dare', 1, 'Stand in the street and wave to every passerby for two minutes.'],
  ['Teens', 'both', 'dare', 1, 'Act like a dog and ask the others to pet you, like a dog.'],
  ['Teens', 'both', 'dare', 1, 'Walk like a runway model on the sidewalk.'],
  ['Teens', 'both', 'dare', 1, 'Hold a sign that says “Honk if you think I’m cute” and stand outside.'],
  ['Teens', 'both', 'dare', 1, 'Dance like crazy to your favorite song.'],
  ['Teens', 'both', 'dare', 1, 'Go outside and check the mailbox and come back inside. Repeat it three times and count the number out loud each time.'],
  ['Teens', 'both', 'dare', 1, 'For the next one hour, you must say “oh, not again!” every time someone says the word “like”.'],
  ['Teens', 'both', 'dare', 1, 'Recite the alphabet backward.'],
  ['Teens', 'both', 'dare', 1, 'Beat an egg on your head.'],
  ['Teens', 'both', 'dare', 1, 'Eat a snack without using your hands.'],
  ['Teens', 'both', 'dare', 1, 'Make a funny hat and wear it on your head for the next two rounds.'],
  ['Teens', 'both', 'dare', 1, 'Make a shirt/skirt of a garbage bag and wear it for the next two rounds.'],
  ['Teens', 'both', 'dare', 1, 'Stand in the chicken pose for the next two rounds.'],
  ['Teens', 'both', 'dare', 1, 'Eat a spoonful of mustard.'],
  ['Teens', 'both', 'dare', 1, 'Imitate each one of the members in the room.'],
  ['Teens', 'both', 'dare', 1, 'Act like your favorite teacher for the next 30 seconds.'],
  ['Teens', 'both', 'dare', 1, 'Eat as much hot sauce as you can.'],
  ['Teens', 'both', 'dare', 1, 'Break up with your girlfriend/boyfriend.'],
  ['Teens', 'both', 'dare', 1, 'Fold yourself like a pretzel.'],
  ['Teens', 'both', 'dare', 1, 'Give the person to your right a piggyback ride.'],
  ['Teens', 'both', 'dare', 1, 'Do a belly dance.'],
  ['Teens', 'both', 'dare', 1, 'Act like the waiter and take snack order from every individual in the group. Serve them and ask if they enjoyed the food.'],
  ['Teens', 'both', 'dare', 1, 'Create an outfit that has every color of the rainbow. You can borrow clothes from the host and the others in the group. Take no more than ten minutes.'],
  ['Teens', 'both', 'dare', 1, 'Call your parents and tell them that they are grounded for a week.'],
  ['Teens', 'both', 'dare', 1, 'For the rest of the night, dance like a ballerina instead of walking.'],
  ['Teens', 'both', 'dare', 1, 'Dance to Auld Lang Syne.'],
  ['Teens', 'both', 'dare', 1, 'Come up with a list of celebrities that each of the other players looks like in under two minutes.'],
  ['Teens', 'both', 'dare', 1, 'Sing the latest pop song in the worst possible way and post the video on YouTube.'],
  ['Teens', 'both', 'dare', 1, 'Tell a bad joke in a really excited tone!'],
  ['Teens', 'both', 'dare', 1, 'Put ice in your shirt and stay still until it melts.'],
  ['Teens', 'both', 'dare', 1, 'Try to lick your elbow while singing a song.'],
  ['Teens', 'both', 'dare', 1, 'Try to touch your nose with your tongue.'],
  ['Teens', 'both', 'dare', 1, 'Fill your mouth with crackers and whistle.'],
  ['Teens', 'both', 'dare', 1, 'Go out and say “I love you” to the first person you meet.'],
  ['Teens', 'both', 'dare', 1, 'Go out and sing a Disney song as loudly as you can.'],
  ['Teens', 'both', 'dare', 1, 'Borrow a cup of sugar from the neighbors.'],
  ['Teens', 'both', 'dare', 1, 'Make a video of you Moonwalking across the room and post it on YouTube.'],
  ['Teens', 'both', 'dare', 1, 'Ask the first person you meet outside on a date.'],
  ['Teens', 'both', 'dare', 1, 'Make a headdress out of toilet paper and promote it on Facebook!'],
  ['Teens', 'both', 'dare', 1, 'Say the alphabet backward in a British accent.'],
  ['Teens', 'both', 'dare', 1, 'For the next two rounds, sing whatever you want to say.'],
  ['Teens', 'both', 'dare', 1, 'Speak in rhyming words for the next three rounds.'],
  ['Teens', 'both', 'dare', 1, 'Repeat everything that the other players say for the next two rounds! (This is fun and annoying too!)'],
  ['Teens', 'both', 'dare', 1, 'Have a tea party with stuffed toys and invite the rest of the group. Act like a five-year old girl while you do.'],
  ['Teens', 'both', 'dare', 1, 'For the next two rounds, speak like you were under water, gasping for air.'],
  ['Teens', 'both', 'dare', 1, 'Call up someone you have a crush on and tell them how much you like them!'],
  ['Teens', 'both', 'dare', 1, 'Use your elbows to update your Facebook status.'],
  ['Teens', 'both', 'dare', 1, 'Dance like a chicken on the lawn!'],
  ['Teens', 'both', 'dare', 1, 'Prank call a restaurant and order every item on the menu!'],
  ['Teens', 'both', 'dare', 1, 'Hold your shoe/or next person’s shoes to your nose for at least 30 seconds.'],
  ['Teens', 'both', 'dare', 1, 'Run around the house banging your chest and yodeling at the same time.'],
  ['Teens', 'both', 'dare', 1, 'Stand in the street and yell “I am (name)! Hear me roar!!”'],
  ['Teens', 'both', 'dare', 1, 'Combine a spoon of peanut butter and hot sauce and eat it.'],
  ['Teens', 'both', 'dare', 1, 'Smell the armpits of the person sitting to your right.'],
  ['Teens', 'both', 'dare', 1, 'Act like a puppy or a seal and let the others feed you.'],
  ['Teens', 'both', 'dare', 1, 'Sing a pop song as if you were in the opera.'],
  ['Teens', 'both', 'dare', 1, 'Go out the front door and do a dramatic death scene, like Daffy Duck of Bugs Bunny would do.'],
  ['Teens', 'both', 'dare', 1, 'Close your eyes, or get blindfolded and open the fridge door. Point to something and let the others feed you that! (Nothing alcoholic or that the player is allergic to.)'],
  ['Teens', 'both', 'dare', 1, 'Go to the neighbor and ask for toilet paper.'],
  ['Teens', 'both', 'dare', 1, 'Call your boyfriend or crush and explain the rules of Monopoly to them.'],
  ['Teens', 'both', 'dare', 1, 'Call your crush and sing a love song like “I can’t help falling in love”.'],
];
